// <auto-generated />
using System;
using HospitalPersonnelSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalPersonnelSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190402012453_sysiteminfo2")]
    partial class sysiteminfo2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysItem", b =>
                {
                    b.Property<Guid>("ItemCode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("ItemName")
                        .IsRequired();

                    b.Property<string>("Spell")
                        .IsRequired();

                    b.HasKey("ItemCode");

                    b.ToTable("SysItem");

                    b.HasData(
                        new
                        {
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemName = "民族",
                            Spell = "MZ"
                        },
                        new
                        {
                            ItemCode = new Guid("627ebe5d-c8d4-40a0-bd19-0d2b849a21b9"),
                            ItemName = "性别",
                            Spell = "XB"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysItemInfo", b =>
                {
                    b.Property<Guid>("ItemKey")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("ItemCode");

                    b.Property<string>("ItemValue")
                        .IsRequired();

                    b.Property<string>("Spell")
                        .IsRequired();

                    b.HasKey("ItemKey");

                    b.HasIndex("ItemCode");

                    b.ToTable("SysItemInfo");

                    b.HasData(
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000001"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "汉族",
                            Spell = "HZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000002"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "蒙古族",
                            Spell = "MGZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000003"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "回族",
                            Spell = "HZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000004"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "藏族",
                            Spell = "ZZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000005"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "维吾尔族",
                            Spell = "WWEZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000006"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "苗族",
                            Spell = "MZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000007"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "彝族",
                            Spell = "YZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000008"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "壮族",
                            Spell = "ZZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000009"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "布依族",
                            Spell = "BYZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000010"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "朝鲜族",
                            Spell = "CXZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000011"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "满族",
                            Spell = "MZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000012"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "侗族",
                            Spell = "DZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000013"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "瑶族",
                            Spell = "YZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000014"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "白族",
                            Spell = "BZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000015"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "土家族",
                            Spell = "TJZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000016"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "哈尼族",
                            Spell = "HNZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000017"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "哈萨克族",
                            Spell = "HSKZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000018"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "傣族",
                            Spell = "TZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000019"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "黎族",
                            Spell = "LZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000020"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "傈僳族",
                            Spell = "LSZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000021"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "佤族",
                            Spell = "WZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000022"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "畲族",
                            Spell = "SZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000023"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "高山族",
                            Spell = "GSZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000024"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "拉祜族",
                            Spell = "LGZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000025"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "水族",
                            Spell = "SZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000026"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "东乡族",
                            Spell = "DXZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000027"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "纳西族",
                            Spell = "NXZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000028"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "景颇族",
                            Spell = "JPZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000029"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "柯尔克孜族",
                            Spell = "HEKZZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000030"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "土族",
                            Spell = "TZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000031"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "达斡尔族",
                            Spell = "DWEZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000032"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "仫佬族",
                            Spell = "MLZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000033"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "羌族",
                            Spell = "QZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000034"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "布朗族",
                            Spell = "BLZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000035"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "撒拉族",
                            Spell = "LSZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000036"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "毛难族",
                            Spell = "MNZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000037"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "仡佬族",
                            Spell = "QLZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000038"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "锡伯族",
                            Spell = "XBZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000039"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "阿昌族",
                            Spell = "ACZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000040"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "普米族",
                            Spell = "PMZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000041"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "塔吉克族",
                            Spell = "TJKZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000042"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "怒族",
                            Spell = "NZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000043"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "乌孜别克族",
                            Spell = "WZBKZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000044"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "俄罗斯族",
                            Spell = "ELSZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000045"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "鄂温克族",
                            Spell = "EWKZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000046"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "崩龙族",
                            Spell = "BLZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000047"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "保安族",
                            Spell = "BAZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000048"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "裕固族",
                            Spell = "YGZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000049"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "京族",
                            Spell = "JZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000050"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "塔塔尔族",
                            Spell = "TTEZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000051"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "独龙族",
                            Spell = "DLZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000052"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "鄂伦春族",
                            Spell = "ELCZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000053"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "赫哲族",
                            Spell = "HZZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000054"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "门巴族",
                            Spell = "MBZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000055"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "珞巴族",
                            Spell = "LBZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000056"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "基诺族",
                            Spell = "JNZ"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000057"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "其他",
                            Spell = "QT"
                        },
                        new
                        {
                            ItemKey = new Guid("9b849977-0000-0000-0000-000000000058"),
                            ItemCode = new Guid("c93d568d-8c7d-424a-abfd-7faec0b12360"),
                            ItemValue = "外国血统中国人士",
                            Spell = "WGXTZGRS"
                        },
                        new
                        {
                            ItemKey = new Guid("216cb274-0000-0000-0000-000000000001"),
                            ItemCode = new Guid("627ebe5d-c8d4-40a0-bd19-0d2b849a21b9"),
                            ItemValue = "男",
                            Spell = "N"
                        },
                        new
                        {
                            ItemKey = new Guid("216cb274-0000-0000-0000-000000000002"),
                            ItemCode = new Guid("627ebe5d-c8d4-40a0-bd19-0d2b849a21b9"),
                            ItemValue = "女",
                            Spell = "N"
                        },
                        new
                        {
                            ItemKey = new Guid("216cb274-0000-0000-0000-000000000003"),
                            ItemCode = new Guid("627ebe5d-c8d4-40a0-bd19-0d2b849a21b9"),
                            ItemValue = "未知",
                            Spell = "WZ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysItemInfo", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.SysItem", "SysItem")
                        .WithMany("SysItemInfos")
                        .HasForeignKey("ItemCode")
                        .HasConstraintName("FK_ItemCode_SysItem")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
