// <auto-generated />
using System;
using HospitalPersonnelSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalPersonnelSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComAdminDuty", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComAdminDuty");

                    b.HasData(
                        new
                        {
                            Code = new Guid("87982a0b-6472-403a-b2cc-f29531a768fd"),
                            Name = "院长",
                            Sort = 1,
                            Spell = "YC,YZ"
                        },
                        new
                        {
                            Code = new Guid("c2d9eaf2-a3f9-4a7f-a3eb-832514c333a1"),
                            Name = "副院长",
                            Sort = 2,
                            Spell = "FYC,FYZ"
                        },
                        new
                        {
                            Code = new Guid("7dc140aa-48f4-431a-a453-35b329ad8dde"),
                            Name = "书记",
                            Sort = 3,
                            Spell = "SJ"
                        },
                        new
                        {
                            Code = new Guid("5644b8b2-e96f-4580-bfdc-96d3cca9977d"),
                            Name = "副书记",
                            Sort = 4,
                            Spell = "FSJ"
                        },
                        new
                        {
                            Code = new Guid("60415184-d114-4319-9017-07df70edaa6f"),
                            Name = "团委书记",
                            Sort = 5,
                            Spell = "TWSJ"
                        },
                        new
                        {
                            Code = new Guid("39a83fd5-a6a7-4bd8-a09d-7bf3b58428cf"),
                            Name = "团委副书记",
                            Sort = 6,
                            Spell = "TWFSJ"
                        },
                        new
                        {
                            Code = new Guid("46812b55-7b90-42bd-ad96-1c671d24dead"),
                            Name = "大科主任",
                            Sort = 7,
                            Spell = "DKZR"
                        },
                        new
                        {
                            Code = new Guid("2921a8a8-caf8-41eb-8f26-b7deb86487f4"),
                            Name = "科主任",
                            Sort = 8,
                            Spell = "KZR"
                        },
                        new
                        {
                            Code = new Guid("35f72ccf-5a27-4de6-8a1d-2ab54efd9ce3"),
                            Name = "副主任",
                            Sort = 9,
                            Spell = "FZR"
                        },
                        new
                        {
                            Code = new Guid("0df02067-9b98-4a72-b1ff-fb5aebd01dc4"),
                            Name = "护士长",
                            Sort = 10,
                            Spell = "HSC,HSZ"
                        },
                        new
                        {
                            Code = new Guid("bcaeaa1f-bfcd-475b-87be-7ddd56d9d8bb"),
                            Name = "副护士长",
                            Sort = 11,
                            Spell = "FHSC,FHSZ"
                        },
                        new
                        {
                            Code = new Guid("f63b0e64-8c18-496c-bcb7-084ca602afd6"),
                            Name = "科员",
                            Sort = 12,
                            Spell = "KY"
                        },
                        new
                        {
                            Code = new Guid("f6de592d-a65f-4e89-bf18-40729bb2529a"),
                            Name = "干事",
                            Sort = 13,
                            Spell = "GS"
                        },
                        new
                        {
                            Code = new Guid("d4356916-eed6-4c84-bf38-3e207b1cd8f5"),
                            Name = "返聘",
                            Sort = 14,
                            Spell = "FP"
                        },
                        new
                        {
                            Code = new Guid("40574e21-beb0-47fd-a754-143abb0a85dd"),
                            Name = "无",
                            Sort = 15,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComDegree", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComDegree");

                    b.HasData(
                        new
                        {
                            Code = new Guid("cff00a02-34fe-4edb-910e-a8279c789bf2"),
                            Name = "博士后",
                            Sort = 1,
                            Spell = "BSH"
                        },
                        new
                        {
                            Code = new Guid("f4b6484e-375c-4b56-bbcc-2921526b7515"),
                            Name = "博士",
                            Sort = 2,
                            Spell = "BS"
                        },
                        new
                        {
                            Code = new Guid("cff3ecd0-3a6c-4345-b334-541b588f1558"),
                            Name = "硕士",
                            Sort = 3,
                            Spell = "SS"
                        },
                        new
                        {
                            Code = new Guid("8706f3c5-77de-4f05-89ed-836abe03ce88"),
                            Name = "学士",
                            Sort = 4,
                            Spell = "XS"
                        },
                        new
                        {
                            Code = new Guid("82fbc87b-2395-456c-8f5d-1c057f4c4f23"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComEducation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComEducation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("c5b558b8-ce10-437d-ab14-21ff32fda67d"),
                            Name = "博士研究生",
                            Sort = 1,
                            Spell = "BSYJS"
                        },
                        new
                        {
                            Code = new Guid("0ac6285e-b0c8-417b-bb36-69a5f05488a2"),
                            Name = "硕士研究生",
                            Sort = 2,
                            Spell = "SSYJS"
                        },
                        new
                        {
                            Code = new Guid("ec171bfd-8ff5-4240-9750-7f6e0a291153"),
                            Name = "本科",
                            Sort = 3,
                            Spell = "BK"
                        },
                        new
                        {
                            Code = new Guid("dd9159b1-b5e1-4bd2-8592-693c3da3de75"),
                            Name = "专科",
                            Sort = 4,
                            Spell = "ZK"
                        },
                        new
                        {
                            Code = new Guid("849e5df0-f441-405e-a6cf-eead95c9de9f"),
                            Name = "中专",
                            Sort = 5,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("0cfe317b-7e3a-4430-8723-14f31f56bc94"),
                            Name = "高中及以下",
                            Sort = 6,
                            Spell = "GZJYX"
                        },
                        new
                        {
                            Code = new Guid("b3c0fe4c-0a6d-4ca7-9684-92ea578667e5"),
                            Name = "技校",
                            Sort = 7,
                            Spell = "JJ,JX"
                        },
                        new
                        {
                            Code = new Guid("400d57e3-cf50-4342-81ed-61abc8d4a73f"),
                            Name = "其他",
                            Sort = 8,
                            Spell = "JT,QT"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComGender", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComGender");

                    b.HasData(
                        new
                        {
                            Code = new Guid("0630a5c8-f534-4f0a-bb7c-6f5d502f6775"),
                            Name = "男",
                            Sort = 1,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("654216e7-20ef-4fd8-91a9-997140d385bd"),
                            Name = "女",
                            Sort = 2,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("f1384219-82c1-47d8-8689-0be7c7f41129"),
                            Name = "未知",
                            Sort = 3,
                            Spell = "WZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComMarriage", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComMarriage");

                    b.HasData(
                        new
                        {
                            Code = new Guid("f74b78e0-6d65-434b-80b3-31e1af8bfe3c"),
                            Name = "未婚",
                            Sort = 1,
                            Spell = "WH"
                        },
                        new
                        {
                            Code = new Guid("bce6742e-1175-4866-b449-e4d1c11a75d1"),
                            Name = "已婚",
                            Sort = 2,
                            Spell = "YH"
                        },
                        new
                        {
                            Code = new Guid("f52b4cd1-59c1-40af-9f5c-2221639f3a69"),
                            Name = "丧偶",
                            Sort = 3,
                            Spell = "SO"
                        },
                        new
                        {
                            Code = new Guid("3454f308-3d1a-4238-b840-33a11e30f0fa"),
                            Name = "离婚",
                            Sort = 4,
                            Spell = "LH"
                        },
                        new
                        {
                            Code = new Guid("6cca4dd0-8fa7-46be-90ab-f6ac0379adde"),
                            Name = "未说明的婚姻状况",
                            Sort = 5,
                            Spell = "WSMDHYZK,WYMDHYZK"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComNation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComNation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("ce17f92b-ee53-4aa6-8f3d-c3b13d865e2d"),
                            Name = "汉族",
                            Sort = 1,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("26c705d8-84c4-4190-8ee7-acab43911bff"),
                            Name = "蒙古族",
                            Sort = 2,
                            Spell = "MGZ"
                        },
                        new
                        {
                            Code = new Guid("ee4d6d4b-88de-4fde-b636-010ea63a5b4a"),
                            Name = "回族",
                            Sort = 3,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("2eae0f9e-036d-4bea-8dde-171eb99f54a1"),
                            Name = "藏族",
                            Sort = 4,
                            Spell = "CZ,ZZ"
                        },
                        new
                        {
                            Code = new Guid("3a6952aa-3015-4b31-aaed-ccb660e4a864"),
                            Name = "维吾尔族",
                            Sort = 5,
                            Spell = "WWEZ"
                        },
                        new
                        {
                            Code = new Guid("740f6ed1-0ce0-4f62-bb54-9d9c55dad8e3"),
                            Name = "苗族",
                            Sort = 6,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("6fa2c84e-5b7a-4ebc-9598-94ff8606c91b"),
                            Name = "彝族",
                            Sort = 7,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("954184ff-29c0-486e-af9a-97e3b84da26f"),
                            Name = "壮族",
                            Sort = 8,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("dc1d7ba0-f55e-411e-843a-d42e71177289"),
                            Name = "布依族",
                            Sort = 9,
                            Spell = "BYZ"
                        },
                        new
                        {
                            Code = new Guid("3de54b02-f4f8-4cd5-961a-0adbaf324c73"),
                            Name = "朝鲜族",
                            Sort = 10,
                            Spell = "CXZ,ZXZ"
                        },
                        new
                        {
                            Code = new Guid("dba2da62-50e8-4b07-ae00-6be79559b301"),
                            Name = "满族",
                            Sort = 11,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("fc55508d-48f6-46cb-b174-04a70206996d"),
                            Name = "侗族",
                            Sort = 12,
                            Spell = "DZ,TZ"
                        },
                        new
                        {
                            Code = new Guid("172712be-98a0-4e4f-8cdd-b5651a776f71"),
                            Name = "瑶族",
                            Sort = 13,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("47e386ce-2719-4f65-8db4-2458f0f34d33"),
                            Name = "白族",
                            Sort = 14,
                            Spell = "BZ"
                        },
                        new
                        {
                            Code = new Guid("5cba272e-0582-49cc-8f83-85ece943e17f"),
                            Name = "土家族",
                            Sort = 15,
                            Spell = "TGZ,TJZ"
                        },
                        new
                        {
                            Code = new Guid("80036137-0fb7-41a2-ad90-26ad16538c42"),
                            Name = "哈尼族",
                            Sort = 16,
                            Spell = "HNZ"
                        },
                        new
                        {
                            Code = new Guid("b983052e-1f79-4d52-904a-43187ae0882b"),
                            Name = "哈萨克族",
                            Sort = 17,
                            Spell = "HSKZ"
                        },
                        new
                        {
                            Code = new Guid("4566040a-1f91-4cbe-9cf8-c5e1acbefab8"),
                            Name = "傣族",
                            Sort = 18,
                            Spell = "DZ"
                        },
                        new
                        {
                            Code = new Guid("ef9936a8-a615-4636-b7b4-919e996a1629"),
                            Name = "黎族",
                            Sort = 19,
                            Spell = "LZ"
                        },
                        new
                        {
                            Code = new Guid("a3e497c2-c08e-422c-8116-60685c499de2"),
                            Name = "傈僳族",
                            Sort = 20,
                            Spell = "LSZ"
                        },
                        new
                        {
                            Code = new Guid("f69a45e4-6f4b-42f3-8368-890258a81769"),
                            Name = "佤族",
                            Sort = 21,
                            Spell = "WZ"
                        },
                        new
                        {
                            Code = new Guid("e2404dae-fd5c-4342-892a-05bf48115fe1"),
                            Name = "畲族",
                            Sort = 22,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("b3bef724-0386-407e-840d-456b38e1746e"),
                            Name = "高山族",
                            Sort = 23,
                            Spell = "GSZ"
                        },
                        new
                        {
                            Code = new Guid("62cec5c1-85ff-4111-b0fc-7cd5ac27efe9"),
                            Name = "拉祜族",
                            Sort = 24,
                            Spell = "LHZ"
                        },
                        new
                        {
                            Code = new Guid("744d4e73-f4e5-4731-b5f3-57be7099c7d7"),
                            Name = "水族",
                            Sort = 25,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("da4065ec-4989-4b48-9334-d68465c947d3"),
                            Name = "东乡族",
                            Sort = 26,
                            Spell = "DXZ"
                        },
                        new
                        {
                            Code = new Guid("c10625ab-1684-4b27-af37-62ccddfd63b5"),
                            Name = "纳西族",
                            Sort = 27,
                            Spell = "NXZ"
                        },
                        new
                        {
                            Code = new Guid("32111b8d-e77f-4a3d-97d0-e7802540a0c6"),
                            Name = "景颇族",
                            Sort = 28,
                            Spell = "JPZ"
                        },
                        new
                        {
                            Code = new Guid("825f27b2-7425-4952-a2af-9b70f9596dec"),
                            Name = "柯尔克孜族",
                            Sort = 29,
                            Spell = "KEKZZ"
                        },
                        new
                        {
                            Code = new Guid("c6ee7cd8-241a-4975-b898-c7bad83ca1ea"),
                            Name = "土族",
                            Sort = 30,
                            Spell = "TZ"
                        },
                        new
                        {
                            Code = new Guid("8c9c7851-e2e9-4bf3-8c17-310c872e3297"),
                            Name = "达斡尔族",
                            Sort = 31,
                            Spell = "DWEZ"
                        },
                        new
                        {
                            Code = new Guid("89e49664-e93c-4052-98bd-791fb1fb4d80"),
                            Name = "仫佬族",
                            Sort = 32,
                            Spell = "MLZ"
                        },
                        new
                        {
                            Code = new Guid("61edbd56-9baa-42b7-9ad9-5a30f5352e6b"),
                            Name = "羌族",
                            Sort = 33,
                            Spell = "QZ"
                        },
                        new
                        {
                            Code = new Guid("0e932375-9ef5-4534-910d-7f6fde59fa85"),
                            Name = "布朗族",
                            Sort = 34,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("025318a9-4c13-40cd-87cc-d090b0c46991"),
                            Name = "撒拉族",
                            Sort = 35,
                            Spell = "SLZ"
                        },
                        new
                        {
                            Code = new Guid("74874774-c46d-4455-bb2f-35e6d06a4a5a"),
                            Name = "毛难族",
                            Sort = 36,
                            Spell = "MNZ"
                        },
                        new
                        {
                            Code = new Guid("3c690c36-4850-4a80-aa55-af1229f73d6a"),
                            Name = "仡佬族",
                            Sort = 37,
                            Spell = "GLZ,YLZ"
                        },
                        new
                        {
                            Code = new Guid("76b50b3a-724f-4745-84b0-4e51d1f9d7da"),
                            Name = "锡伯族",
                            Sort = 38,
                            Spell = "XBZ"
                        },
                        new
                        {
                            Code = new Guid("bdccf2af-4055-4d35-a108-df6c43a02196"),
                            Name = "阿昌族",
                            Sort = 39,
                            Spell = "ACZ,ECZ"
                        },
                        new
                        {
                            Code = new Guid("e2453a91-963e-46c4-a035-db3a2e3080ee"),
                            Name = "普米族",
                            Sort = 40,
                            Spell = "PMZ"
                        },
                        new
                        {
                            Code = new Guid("a32e26c4-569b-4c48-830e-2e853ddaeb34"),
                            Name = "塔吉克族",
                            Sort = 41,
                            Spell = "DJKZ,TJKZ"
                        },
                        new
                        {
                            Code = new Guid("75237aad-ce10-4424-a5f3-d39e5dd64938"),
                            Name = "怒族",
                            Sort = 42,
                            Spell = "NZ"
                        },
                        new
                        {
                            Code = new Guid("0a29476d-7c6a-4042-9973-4ed7b203d4f2"),
                            Name = "乌孜别克族",
                            Sort = 43,
                            Spell = "WZBKZ"
                        },
                        new
                        {
                            Code = new Guid("bc00f0ef-fb13-45f0-b519-595d2f9eba01"),
                            Name = "俄罗斯族",
                            Sort = 44,
                            Spell = "ELSZ"
                        },
                        new
                        {
                            Code = new Guid("57d74f6e-3d3f-445d-a8de-f235166ada20"),
                            Name = "鄂温克族",
                            Sort = 45,
                            Spell = "EWKZ"
                        },
                        new
                        {
                            Code = new Guid("c60508c0-e5d9-419d-af6e-896c75fd709c"),
                            Name = "崩龙族",
                            Sort = 46,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("bd469f69-b5db-4307-b0e4-d4fdb491c994"),
                            Name = "保安族",
                            Sort = 47,
                            Spell = "BAZ"
                        },
                        new
                        {
                            Code = new Guid("02bdbce2-ae42-4d8d-b1b9-c3895b2b8a9f"),
                            Name = "裕固族",
                            Sort = 48,
                            Spell = "YGZ"
                        },
                        new
                        {
                            Code = new Guid("0b6a1d95-e2b9-4580-976f-cf68410de1c7"),
                            Name = "京族",
                            Sort = 49,
                            Spell = "JZ"
                        },
                        new
                        {
                            Code = new Guid("fd957d18-c306-4f38-b579-a602884846f2"),
                            Name = "塔塔尔族",
                            Sort = 50,
                            Spell = "DDEZ,TDEZ,DTEZ,TTEZ"
                        },
                        new
                        {
                            Code = new Guid("f6af5586-c80f-40ed-8076-1a5460dd1bdd"),
                            Name = "独龙族",
                            Sort = 51,
                            Spell = "DLZ"
                        },
                        new
                        {
                            Code = new Guid("0254d292-9d71-4630-bb42-d8d58a07ae6c"),
                            Name = "鄂伦春族",
                            Sort = 52,
                            Spell = "ELCZ"
                        },
                        new
                        {
                            Code = new Guid("9a3068c1-b136-40f7-8354-3ee482f1b706"),
                            Name = "赫哲族",
                            Sort = 53,
                            Spell = "HZZ"
                        },
                        new
                        {
                            Code = new Guid("43118796-f4e1-4fb6-9a08-36efa30ffa27"),
                            Name = "门巴族",
                            Sort = 54,
                            Spell = "MBZ"
                        },
                        new
                        {
                            Code = new Guid("1b5c0484-7e18-4d60-94bd-75455b5415e0"),
                            Name = "珞巴族",
                            Sort = 55,
                            Spell = "LBZ"
                        },
                        new
                        {
                            Code = new Guid("a5d60ce1-6377-4ebc-83a8-e6df83a76897"),
                            Name = "基诺族",
                            Sort = 56,
                            Spell = "JNZ"
                        },
                        new
                        {
                            Code = new Guid("f2a1a5dc-eff9-4b82-a8a7-9de0004c04ef"),
                            Name = "其他",
                            Sort = 57,
                            Spell = "JT,QT"
                        },
                        new
                        {
                            Code = new Guid("6d0371ab-e9b7-4270-bd3a-493d78833e82"),
                            Name = "外国血统中国人士",
                            Sort = 58,
                            Spell = "WGXTZGRS"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComPolitical", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComPolitical");

                    b.HasData(
                        new
                        {
                            Code = new Guid("37ad68f0-54aa-4c03-ab08-10a918c4212b"),
                            Name = "中共党员",
                            Sort = 1,
                            Spell = "ZGDY"
                        },
                        new
                        {
                            Code = new Guid("db49da61-7b25-4db0-ad0a-5ab053c20593"),
                            Name = "中共预备党员",
                            Sort = 2,
                            Spell = "ZGYBDY"
                        },
                        new
                        {
                            Code = new Guid("0e140c62-ca4a-4617-b3a2-ca02e60b8b49"),
                            Name = "共青团员",
                            Sort = 3,
                            Spell = "GQTY"
                        },
                        new
                        {
                            Code = new Guid("0bef4ce4-e142-44f4-9a3b-a6db69c0087e"),
                            Name = "民革党员",
                            Sort = 4,
                            Spell = "MGDY,MJDY"
                        },
                        new
                        {
                            Code = new Guid("35900c9d-2334-41d9-9cee-6d124cfe15c0"),
                            Name = "民盟盟员",
                            Sort = 5,
                            Spell = "MMMY"
                        },
                        new
                        {
                            Code = new Guid("6dc94e40-3726-4de3-a89b-ec500f600b66"),
                            Name = "民建会员",
                            Sort = 6,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("83178a88-6576-45cc-bb78-88a43cf4401c"),
                            Name = "民进会员",
                            Sort = 7,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("550b5a20-74a9-4586-be8b-ee8818647715"),
                            Name = "农工党党员",
                            Sort = 8,
                            Spell = "NGDDY"
                        },
                        new
                        {
                            Code = new Guid("012f637c-2b3e-4c75-858e-7a5f9477815d"),
                            Name = "致公党党员",
                            Sort = 9,
                            Spell = "ZGDDY"
                        },
                        new
                        {
                            Code = new Guid("5816c78b-5187-4c85-959a-59bc50062a2d"),
                            Name = "九三学社社员",
                            Sort = 10,
                            Spell = "JSXSSY"
                        },
                        new
                        {
                            Code = new Guid("71fc9dd7-e7a1-49b2-ad99-bf3f5d043718"),
                            Name = "台盟盟员",
                            Sort = 11,
                            Spell = "TMMY"
                        },
                        new
                        {
                            Code = new Guid("64c693ab-475d-437c-b653-d04a2c7065f8"),
                            Name = "无党派人士",
                            Sort = 12,
                            Spell = "MDPRS,WDPRS"
                        },
                        new
                        {
                            Code = new Guid("8e871348-b291-44e3-9aff-534cfe8eb4cf"),
                            Name = "群众",
                            Sort = 13,
                            Spell = "QZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("LevelCode");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("LevelCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("ComProfessionTitle");

                    b.HasData(
                        new
                        {
                            Code = new Guid("3572d2cd-b0be-44a2-9d21-8f90198684ee"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任医师",
                            Sort = 1,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("172da8e9-f6b6-481d-9d6c-aad1a7acb67c"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任药师",
                            Sort = 2,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("e7624edf-e523-44de-ad86-6be4fe924e12"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任护师",
                            Sort = 3,
                            Spell = "ZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("483c24ea-0d17-47bd-ae93-507c08edad47"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任技师",
                            Sort = 4,
                            Spell = "ZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("c7299e61-6f35-4fae-a32c-11401f89c9a5"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任医师",
                            Sort = 5,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("89f5ff32-9f1a-4a94-8bdd-a023c20057c0"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任药师",
                            Sort = 6,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("a3a48790-73db-4cef-a928-ed606e28689d"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任护师",
                            Sort = 7,
                            Spell = "FZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("43f7d4a5-0d67-4d7b-a6b7-8af2ca6e2bf6"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任技师",
                            Sort = 8,
                            Spell = "FZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("a9d9561c-75d8-473b-b759-76dac1046899"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主治医师",
                            Sort = 9,
                            Spell = "ZZYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("25719e70-0d8f-4c1d-9f81-5755f94c979e"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管药师",
                            Sort = 10,
                            Spell = "ZGYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("0c957da8-6b27-45af-83ec-342e186442d5"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管护师",
                            Sort = 11,
                            Spell = "ZGHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("80d1cb2d-6e71-409d-992c-40473777fe77"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管技师",
                            Sort = 12,
                            Spell = "ZGJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("dc98a5f0-109c-4dac-b70a-562800bee327"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医师",
                            Sort = 13,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("f1c3b99d-8c48-40f8-a8e3-55fb059c346b"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医士",
                            Sort = 14,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("741d6189-e71c-4b32-9e2b-c077a7defe03"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药师",
                            Sort = 15,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("606dd894-d68b-4208-b1d6-6f41ad8e52d2"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药士",
                            Sort = 16,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("5723497f-ada6-404b-a287-d359c496b3fe"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护师",
                            Sort = 17,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("05e76e6d-4ef7-4c86-adfa-6e1f64ac0258"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护士",
                            Sort = 18,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("73959df0-01c2-4f33-a73f-fc257e07bdf2"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技师",
                            Sort = 19,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("e3c47067-00a9-42f5-a502-5c2244092004"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技士",
                            Sort = 20,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("4a8a8a1c-d30c-4e4e-aac9-9f35c2155377"),
                            LevelCode = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无职称",
                            Sort = 21,
                            Spell = "MZC,WZC",
                            TypeCode = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleLevel");

                    b.HasData(
                        new
                        {
                            Code = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "正高级",
                            Sort = 1,
                            Spell = "ZGJ"
                        },
                        new
                        {
                            Code = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副高级",
                            Sort = 2,
                            Spell = "FGJ"
                        },
                        new
                        {
                            Code = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "中级",
                            Sort = 3,
                            Spell = "ZJ"
                        },
                        new
                        {
                            Code = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "初级",
                            Sort = 4,
                            Spell = "CJ"
                        },
                        new
                        {
                            Code = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768"),
                            Name = "卫生技术人员",
                            Sort = 1,
                            Spell = "WSJSRY,WSJZRY"
                        },
                        new
                        {
                            Code = new Guid("2cc60d12-381c-45ab-956d-60089e51b22d"),
                            Name = "高等学校教师",
                            Sort = 2,
                            Spell = "GDXJJS,GDXXJS"
                        },
                        new
                        {
                            Code = new Guid("92829a97-b381-4698-8f05-6869a5c4fc84"),
                            Name = "中等专业学校教师",
                            Sort = 3,
                            Spell = "ZDZYXJJS,ZDZYXXJS"
                        },
                        new
                        {
                            Code = new Guid("e8a22bf0-7f42-4d66-89c5-2fa3fd5205fd"),
                            Name = "技工学校教师",
                            Sort = 4,
                            Spell = "JGXJJS,JGXXJS"
                        },
                        new
                        {
                            Code = new Guid("4c3affbf-5111-4973-8fbd-6b07fb9f63dd"),
                            Name = "中学教师",
                            Sort = 5,
                            Spell = "ZXJS"
                        },
                        new
                        {
                            Code = new Guid("82544c43-a457-486a-a2cb-4b717eee17b8"),
                            Name = "小学（幼儿园）教师",
                            Sort = 6,
                            Spell = "XX（YEY）JS"
                        },
                        new
                        {
                            Code = new Guid("1f1bffb9-7819-4b9c-a7f3-220c744a244a"),
                            Name = "自然科学研究人员",
                            Sort = 7,
                            Spell = "ZRKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("db7df432-def4-466c-bb49-00c1cd9688b9"),
                            Name = "社会科学研究人员",
                            Sort = 8,
                            Spell = "SHKXYJRY,SKKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("910f39af-b690-4a8a-aa11-62a495d8c4e7"),
                            Name = "工程技术人员",
                            Sort = 9,
                            Spell = "GCJSRY,GCJZRY"
                        },
                        new
                        {
                            Code = new Guid("a397e95f-b3bd-4071-b651-fec0aea062ca"),
                            Name = "实验技术人员",
                            Sort = 10,
                            Spell = "SYJSRY,SYJZRY"
                        },
                        new
                        {
                            Code = new Guid("fe237910-3e80-461c-ad42-69e9b5f2287f"),
                            Name = "农业技术人员",
                            Sort = 11,
                            Spell = "NYJSRY,NYJZRY"
                        },
                        new
                        {
                            Code = new Guid("a92e097b-fa47-45a9-b80f-ed7114782061"),
                            Name = "经济专业人员",
                            Sort = 12,
                            Spell = "JJZYRY"
                        },
                        new
                        {
                            Code = new Guid("c24319b0-86ef-4da3-b87f-4f1d4af3910e"),
                            Name = "会计专业人员",
                            Sort = 13,
                            Spell = "HJZYRY,KJZYRY"
                        },
                        new
                        {
                            Code = new Guid("dcd9d524-8fa6-4f2f-9d79-db7019ac12db"),
                            Name = "审计专业人员",
                            Sort = 14,
                            Spell = "SJZYRY"
                        },
                        new
                        {
                            Code = new Guid("f681abea-1306-4949-bb53-f62b9ab1234e"),
                            Name = "统计专业人员",
                            Sort = 15,
                            Spell = "TJZYRY"
                        },
                        new
                        {
                            Code = new Guid("bd3492c1-8051-4ab4-89f4-1a6cf03d2138"),
                            Name = "新闻专业人员",
                            Sort = 16,
                            Spell = "XWZYRY"
                        },
                        new
                        {
                            Code = new Guid("2ad1a450-78de-4b15-87f2-cf75640c26c7"),
                            Name = "出版专业人员",
                            Sort = 17,
                            Spell = "CBZYRY"
                        },
                        new
                        {
                            Code = new Guid("9e7b3f3f-1b0a-4d50-aba1-32735087f5fa"),
                            Name = "图书资料专业人员",
                            Sort = 18,
                            Spell = "TSZLZYRY"
                        },
                        new
                        {
                            Code = new Guid("5580d019-858f-49fe-a0b3-0b13dc503d0a"),
                            Name = "文物博物专业人员",
                            Sort = 19,
                            Spell = "WWBWZYRY"
                        },
                        new
                        {
                            Code = new Guid("0b964833-02cc-4560-9cb4-45aeea903537"),
                            Name = "档案专业人员",
                            Sort = 20,
                            Spell = "DAZYRY"
                        },
                        new
                        {
                            Code = new Guid("ea43c76a-bf43-4d4d-b6b6-329202a9f33c"),
                            Name = "广播电视播音人员",
                            Sort = 21,
                            Spell = "ABDSBYRY,GBDSBYRY"
                        },
                        new
                        {
                            Code = new Guid("3d8ede7d-2297-44bd-8f8e-bc910cc20703"),
                            Name = "翻译人员",
                            Sort = 22,
                            Spell = "FYRY"
                        },
                        new
                        {
                            Code = new Guid("fd5a11e2-4872-4cb8-9596-80362e1438bb"),
                            Name = "律师",
                            Sort = 23,
                            Spell = "LS"
                        },
                        new
                        {
                            Code = new Guid("001e00a2-f287-4ccb-9e0b-d2907cac7f0f"),
                            Name = "公证员",
                            Sort = 24,
                            Spell = "GZY"
                        },
                        new
                        {
                            Code = new Guid("408fc627-234e-47d1-b479-41a3cf8dae93"),
                            Name = "海关人员",
                            Sort = 25,
                            Spell = "HGRY"
                        },
                        new
                        {
                            Code = new Guid("27e13aee-8bdf-40c9-bf5d-76fee555b387"),
                            Name = "船舶技术人员",
                            Sort = 26,
                            Spell = "CBJSRY,CBJZRY"
                        },
                        new
                        {
                            Code = new Guid("2933457b-acf4-4587-8069-27bbe977e99e"),
                            Name = "民用航空飞行技术人员",
                            Sort = 27,
                            Spell = "MYHKFHJSRY,MYHKFXJSRY,MYHKFHJZRY,MYHKFXJZRY"
                        },
                        new
                        {
                            Code = new Guid("16bbdff0-044b-4368-8dbb-2580be30be41"),
                            Name = "艺术专业人员",
                            Sort = 28,
                            Spell = "YSZYRY,YZZYRY"
                        },
                        new
                        {
                            Code = new Guid("40ae0347-100b-40f4-9a99-5ce801b91ee8"),
                            Name = "工艺美术专业人员",
                            Sort = 29,
                            Spell = "GYMSZYRY,GYMZZYRY"
                        },
                        new
                        {
                            Code = new Guid("81be1edc-70b5-4ac4-8a95-31f3bbcdfafe"),
                            Name = "体育教练员",
                            Sort = 30,
                            Spell = "TYJLY"
                        },
                        new
                        {
                            Code = new Guid("b815b01d-0923-478a-88ef-3cb3d80ac254"),
                            Name = "思想政治工作人员",
                            Sort = 31,
                            Spell = "SXZZGZRY"
                        },
                        new
                        {
                            Code = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c"),
                            Name = "无",
                            Sort = 32,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysDept", b =>
                {
                    b.Property<string>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("DeptName");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("DeptCode");

                    b.ToTable("SysDept");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.Property<string>("EmpCode")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdminDutyCode");

                    b.Property<int>("Age");

                    b.Property<string>("BankCard");

                    b.Property<string>("BirthAdd");

                    b.Property<DateTime>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateEmp");

                    b.Property<Guid?>("DegreeCode");

                    b.Property<string>("DeptCode")
                        .IsRequired();

                    b.Property<Guid?>("EducationCode");

                    b.Property<DateTime?>("EducationDate");

                    b.Property<string>("EmpName")
                        .IsRequired();

                    b.Property<Guid>("GenderCode");

                    b.Property<DateTime?>("GraduationDate");

                    b.Property<string>("HomeAdd");

                    b.Property<int>("HospitalAge");

                    b.Property<DateTime>("HospitalDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IdentityAdd");

                    b.Property<string>("IdentityCard")
                        .IsRequired();

                    b.Property<bool>("IsPost")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStop")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("MarriageCode");

                    b.Property<Guid>("NationCode");

                    b.Property<string>("NativePlace");

                    b.Property<string>("OldName");

                    b.Property<string>("OpenBank");

                    b.Property<string>("Photo");

                    b.Property<Guid>("PoliticalCode");

                    b.Property<DateTime?>("PoliticalDate");

                    b.Property<string>("Practice");

                    b.Property<DateTime?>("PracticeDate");

                    b.Property<Guid?>("ProfessionTitleCode");

                    b.Property<Guid?>("ProfessionTitleLevelCode");

                    b.Property<Guid?>("ProfessionTitleTypeCode");

                    b.Property<string>("Remark");

                    b.Property<string>("School");

                    b.Property<string>("SchoolMajor");

                    b.Property<string>("Spell");

                    b.Property<string>("Telephone");

                    b.Property<Guid>("TypeCode");

                    b.Property<int>("WorkAge");

                    b.Property<DateTime?>("WorkDate");

                    b.HasKey("EmpCode");

                    b.HasIndex("AdminDutyCode");

                    b.HasIndex("DegreeCode");

                    b.HasIndex("DeptCode");

                    b.HasIndex("EducationCode");

                    b.HasIndex("GenderCode");

                    b.HasIndex("MarriageCode");

                    b.HasIndex("NationCode");

                    b.HasIndex("PoliticalCode");

                    b.HasIndex("ProfessionTitleCode");

                    b.HasIndex("ProfessionTitleLevelCode");

                    b.HasIndex("ProfessionTitleTypeCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysEmp");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmpType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysEmpType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("bb97bcdd-1cf0-4e9f-94b4-925a30ed331d"),
                            Name = "在编人员",
                            Sort = 1,
                            Spell = "ZBRY"
                        },
                        new
                        {
                            Code = new Guid("6fb7e11f-2ae1-419f-ae8e-2e6543326039"),
                            Name = "人事代理",
                            Sort = 2,
                            Spell = "RSDL"
                        },
                        new
                        {
                            Code = new Guid("20d948fc-7f06-4134-b83f-4a957996f51d"),
                            Name = "临时人员",
                            Sort = 3,
                            Spell = "LSRY"
                        },
                        new
                        {
                            Code = new Guid("bd74f213-bc03-4358-9061-38eadb99536e"),
                            Name = "离退人员",
                            Sort = 4,
                            Spell = "LTRY"
                        },
                        new
                        {
                            Code = new Guid("ab407b34-9559-4906-b598-7d6e6ec600fa"),
                            Name = "辞职人员",
                            Sort = 5,
                            Spell = "CZRY"
                        },
                        new
                        {
                            Code = new Guid("d465f5fa-538a-42d1-b873-b66fac5c2c22"),
                            Name = "返聘人员",
                            Sort = 6,
                            Spell = "FPRY"
                        },
                        new
                        {
                            Code = new Guid("96ddfb3a-311e-4547-9093-9c772f5838d3"),
                            Name = "调出人员",
                            Sort = 7,
                            Spell = "DCRY,TCRY"
                        },
                        new
                        {
                            Code = new Guid("4cb8ad1f-dfe0-45c0-8343-200f0ace364b"),
                            Name = "除名人员",
                            Sort = 8,
                            Spell = "CMRY"
                        },
                        new
                        {
                            Code = new Guid("b68eb4d5-f0fb-435e-9629-042e04ed5edf"),
                            Name = "实习进修",
                            Sort = 9,
                            Spell = "SXJX"
                        },
                        new
                        {
                            Code = new Guid("c3e49e81-4910-44af-8109-3fda1755f2f5"),
                            Name = "借出人员",
                            Sort = 10,
                            Spell = "JCRY"
                        },
                        new
                        {
                            Code = new Guid("5b89349a-7ec7-4d1a-b790-4b5a4cb37475"),
                            Name = "长期出国人员",
                            Sort = 11,
                            Spell = "CJCGRY,ZJCGRY,CQCGRY,ZQCGRY"
                        },
                        new
                        {
                            Code = new Guid("3637fca5-7cea-4c13-a523-797a97afcbac"),
                            Name = "自动离职人员",
                            Sort = 12,
                            Spell = "ZDLZRY"
                        },
                        new
                        {
                            Code = new Guid("a949359f-f90e-4394-821e-58c8dc0fce94"),
                            Name = "停薪留职人员",
                            Sort = 13,
                            Spell = "TXLZRY"
                        },
                        new
                        {
                            Code = new Guid("c26e1bb7-0e70-4ecb-8361-bbcbe3eb3414"),
                            Name = "编外离岗人员",
                            Sort = 14,
                            Spell = "BWLGRY"
                        },
                        new
                        {
                            Code = new Guid("fea8c0d1-ebcd-4178-a292-0564742a9e3c"),
                            Name = "内部退养",
                            Sort = 15,
                            Spell = "NBTY"
                        },
                        new
                        {
                            Code = new Guid("440ad1b9-4aa1-4c4f-a42b-00fd4b072323"),
                            Name = "试用人员",
                            Sort = 16,
                            Spell = "SYRY"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Action");

                    b.Property<string>("Controller");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysNavbar");

                    b.HasData(
                        new
                        {
                            Code = new Guid("d35f6cc5-9171-428a-b841-5bd69986b9db"),
                            Action = "Index",
                            Controller = "SysNavbarType",
                            Name = "菜单类别",
                            Sort = 1,
                            Spell = "CCLB,CDLB,CSLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("e36df6ed-0dc0-4972-9d47-f17b55f972f8"),
                            Action = "Index",
                            Controller = "SysNavbar",
                            Name = "菜单",
                            Sort = 2,
                            Spell = "CC,CD,CS",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("2b295c68-ec11-4c12-a475-b0e1959d4bd4"),
                            Action = "Index",
                            Controller = "ComGender",
                            Name = "性别",
                            Sort = 3,
                            Spell = "XB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("b72755eb-5ece-4c7a-8271-617ff45bda85"),
                            Action = "Index",
                            Controller = "ComNation",
                            Name = "民族",
                            Sort = 4,
                            Spell = "MZ",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("29a846eb-2161-4a6d-a2a2-684120cef2c9"),
                            Action = "Index",
                            Controller = "ComPolitical",
                            Name = "政治面貌",
                            Sort = 5,
                            Spell = "ZZMM",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("f4e50ea0-b522-485f-9791-914783de91b8"),
                            Action = "Index",
                            Controller = "ComProfessionTitleType",
                            Name = "职称系列",
                            Sort = 6,
                            Spell = "ZCJL,ZCXL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("482e2005-2f0f-4766-a7e8-a18126f7f0fc"),
                            Action = "Index",
                            Controller = "ComProfessionTitleLevel",
                            Name = "职称级别",
                            Sort = 7,
                            Spell = "ZCJB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("2ab63b5d-014a-4d37-979c-b6a6c28ef3f8"),
                            Action = "Index",
                            Controller = "ComProfessionTitle",
                            Name = "职称",
                            Sort = 8,
                            Spell = "ZC",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("2a2670e6-ab5a-4422-8b5e-a44b18f6d70e"),
                            Action = "Index",
                            Controller = "ComAdminDuty",
                            Name = "行政职务",
                            Sort = 9,
                            Spell = "HZZW,XZZW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("ddf6d657-b15e-488f-820b-c49dc66c07d7"),
                            Action = "Index",
                            Controller = "SysEmpType",
                            Name = "人员类别",
                            Sort = 10,
                            Spell = "RYLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("1690dbdf-e77d-40c4-8d49-b411aded3db4"),
                            Action = "Index",
                            Controller = "ComEducation",
                            Name = "学历",
                            Sort = 11,
                            Spell = "XL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("e93cc34f-07ae-4da4-a7c8-0600d40ad98f"),
                            Action = "Index",
                            Controller = "ComDegree",
                            Name = "学位",
                            Sort = 12,
                            Spell = "XW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("5dd44a1e-ab5b-49f3-8a2a-d0fe8fb3b4e1"),
                            Action = "Index",
                            Controller = "ComMarriage",
                            Name = "婚姻状况",
                            Sort = 13,
                            Spell = "HYZK",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("d36fdad2-004d-4a3a-bcc3-30cdbbd6b9f9"),
                            Action = "Index",
                            Controller = "SysDept",
                            Name = "科室信息",
                            Sort = 14,
                            Spell = "KSXX",
                            TypeCode = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e")
                        },
                        new
                        {
                            Code = new Guid("8dfc9898-dbe4-48ab-bbcc-b758715af43a"),
                            Action = "Index",
                            Controller = "SysEmp",
                            Name = "人员管理",
                            Sort = 15,
                            Spell = "RYGL",
                            TypeCode = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbarType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysNavbarType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc"),
                            Name = "基础数据维护",
                            Sort = 1,
                            Spell = "JCSJWH"
                        },
                        new
                        {
                            Code = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e"),
                            Name = "机构管理",
                            Sort = 2,
                            Spell = "JGGL"
                        },
                        new
                        {
                            Code = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993"),
                            Name = "人事档案",
                            Sort = 3,
                            Spell = "RSDA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("LevelCode")
                        .HasConstraintName("FK_LevelCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComAdminDuty", "ComAdminDuty")
                        .WithMany("SysEmps")
                        .HasForeignKey("AdminDutyCode")
                        .HasConstraintName("FK_AdminDutyCode_ComAdminDuty_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComDegree", "ComDegree")
                        .WithMany("SysEmps")
                        .HasForeignKey("DegreeCode")
                        .HasConstraintName("FK_DegreeCode_ComDegree_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysDept", "SysDept")
                        .WithMany("SysEmps")
                        .HasForeignKey("DeptCode")
                        .HasConstraintName("FK_DeptCode_SysDept_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComEducation", "ComEducation")
                        .WithMany("SysEmps")
                        .HasForeignKey("EducationCode")
                        .HasConstraintName("FK_EducationCode_ComEducation_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComGender", "ComGender")
                        .WithMany("SysEmps")
                        .HasForeignKey("GenderCode")
                        .HasConstraintName("FK_GenderCode_ComGender_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComMarriage", "ComMarriage")
                        .WithMany("SysEmps")
                        .HasForeignKey("MarriageCode")
                        .HasConstraintName("FK_MarriageCode_ComMarriage_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComNation", "ComNation")
                        .WithMany("SysEmps")
                        .HasForeignKey("NationCode")
                        .HasConstraintName("FK_NationCode_ComNation_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComPolitical", "ComPolitical")
                        .WithMany("SysEmps")
                        .HasForeignKey("PoliticalCode")
                        .HasConstraintName("FK_PoliticalCode_ComPolitical_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitle", "ComProfessionTitle")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleCode")
                        .HasConstraintName("FK_PTCode_ComProfessionTitle_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleLevelCode")
                        .HasConstraintName("FK_PTLCode_ComProfessionTitleLevel_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleTypeCode")
                        .HasConstraintName("FK_PTTCode_ComProfessionTitleType_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysEmpType", "SysEmpType")
                        .WithMany("SysEmps")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysEmpType_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.SysNavbarType", "SysNavbarType")
                        .WithMany("SysNavbars")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysNavbarType_SysNavbar")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
