// <auto-generated />
using System;
using HospitalPersonnelSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalPersonnelSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComAdminDuty", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComAdminDuty");

                    b.HasData(
                        new
                        {
                            Code = new Guid("520633ee-c48b-4db6-aaa9-3382899b0e42"),
                            Name = "院长",
                            Sort = 1,
                            Spell = "YC,YZ"
                        },
                        new
                        {
                            Code = new Guid("1988ddf2-8fcc-4347-9380-f357e9822a98"),
                            Name = "副院长",
                            Sort = 2,
                            Spell = "FYC,FYZ"
                        },
                        new
                        {
                            Code = new Guid("9b823378-d715-4d1b-82b1-49f56a602f32"),
                            Name = "书记",
                            Sort = 3,
                            Spell = "SJ"
                        },
                        new
                        {
                            Code = new Guid("b19f79a9-adea-4955-a0df-841ae471f83b"),
                            Name = "副书记",
                            Sort = 4,
                            Spell = "FSJ"
                        },
                        new
                        {
                            Code = new Guid("059b1771-8cf8-41d6-8325-5dd9ac140c87"),
                            Name = "团委书记",
                            Sort = 5,
                            Spell = "TWSJ"
                        },
                        new
                        {
                            Code = new Guid("55deea6e-5ca1-4d0e-823d-c04a17aa3868"),
                            Name = "团委副书记",
                            Sort = 6,
                            Spell = "TWFSJ"
                        },
                        new
                        {
                            Code = new Guid("f893a978-ba55-4f49-b234-124981ba0760"),
                            Name = "大科主任",
                            Sort = 7,
                            Spell = "DKZR"
                        },
                        new
                        {
                            Code = new Guid("0e570ef2-9f7f-40c2-b208-8cfa7561694d"),
                            Name = "科主任",
                            Sort = 8,
                            Spell = "KZR"
                        },
                        new
                        {
                            Code = new Guid("9b4f29a0-fcec-4151-9b55-ca0275449f96"),
                            Name = "副主任",
                            Sort = 9,
                            Spell = "FZR"
                        },
                        new
                        {
                            Code = new Guid("fa86e41a-b4d3-4f16-881d-b4cd9241295f"),
                            Name = "护士长",
                            Sort = 10,
                            Spell = "HSC,HSZ"
                        },
                        new
                        {
                            Code = new Guid("0f0ef0bf-0c1d-4375-8d1d-c83fb9d56ace"),
                            Name = "副护士长",
                            Sort = 11,
                            Spell = "FHSC,FHSZ"
                        },
                        new
                        {
                            Code = new Guid("42f61d84-5911-4ee5-8221-8d60754a70c4"),
                            Name = "科员",
                            Sort = 12,
                            Spell = "KY"
                        },
                        new
                        {
                            Code = new Guid("b1004de7-dd15-4029-83c6-6e39d4ceb601"),
                            Name = "干事",
                            Sort = 13,
                            Spell = "GS"
                        },
                        new
                        {
                            Code = new Guid("8e8adf37-45a2-4ea4-ab5a-ee37a0b3fec9"),
                            Name = "返聘",
                            Sort = 14,
                            Spell = "FP"
                        },
                        new
                        {
                            Code = new Guid("40574e21-beb0-47fd-a754-143abb0a85dd"),
                            Name = "无",
                            Sort = 15,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComDegree", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComDegree");

                    b.HasData(
                        new
                        {
                            Code = new Guid("b48d03cf-9647-4957-a7a9-58d1914309b1"),
                            Name = "博士后",
                            Sort = 1,
                            Spell = "BSH"
                        },
                        new
                        {
                            Code = new Guid("84308527-af9b-46f7-946d-1e353e9098f5"),
                            Name = "博士",
                            Sort = 2,
                            Spell = "BS"
                        },
                        new
                        {
                            Code = new Guid("b8647faf-c493-4b31-aefc-59490635a24c"),
                            Name = "硕士",
                            Sort = 3,
                            Spell = "SS"
                        },
                        new
                        {
                            Code = new Guid("0f3aa531-8244-4cb5-bba2-30d7414625b1"),
                            Name = "学士",
                            Sort = 4,
                            Spell = "XS"
                        },
                        new
                        {
                            Code = new Guid("6b2ea297-6c7b-4a9c-bfeb-9a50a1e86d2c"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComEducation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComEducation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("80ea3174-7fda-4692-9ec2-3db8495588bc"),
                            Name = "博士研究生",
                            Sort = 1,
                            Spell = "BSYJS"
                        },
                        new
                        {
                            Code = new Guid("cddcdfb2-24e5-46b8-82ec-3f43791fcc32"),
                            Name = "硕士研究生",
                            Sort = 2,
                            Spell = "SSYJS"
                        },
                        new
                        {
                            Code = new Guid("d7558a54-43be-4303-bf11-08f2bbafffa6"),
                            Name = "本科",
                            Sort = 3,
                            Spell = "BK"
                        },
                        new
                        {
                            Code = new Guid("79f5e3cd-af4a-4527-8878-41a22bd79d46"),
                            Name = "专科",
                            Sort = 4,
                            Spell = "ZK"
                        },
                        new
                        {
                            Code = new Guid("5ccfbbd8-0f8a-4f65-93bf-799f075bfb86"),
                            Name = "中专",
                            Sort = 5,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("e344ad42-eb61-417e-804d-89c71eca7e6c"),
                            Name = "高中及以下",
                            Sort = 6,
                            Spell = "GZJYX"
                        },
                        new
                        {
                            Code = new Guid("47ac947a-7fbb-4a92-96b8-f0c75ef136aa"),
                            Name = "技校",
                            Sort = 7,
                            Spell = "JJ,JX"
                        },
                        new
                        {
                            Code = new Guid("1f8000e0-d062-4466-97db-040474162fab"),
                            Name = "其他",
                            Sort = 8,
                            Spell = "JT,QT"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComGender", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComGender");

                    b.HasData(
                        new
                        {
                            Code = new Guid("07fa2344-50aa-4dba-9962-8779ef6ecc60"),
                            Name = "男",
                            Sort = 1,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("c054f047-5fbe-4dc3-ad3c-32037e18b383"),
                            Name = "女",
                            Sort = 2,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("f1384219-82c1-47d8-8689-0be7c7f41129"),
                            Name = "未知",
                            Sort = 3,
                            Spell = "WZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComMarriage", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComMarriage");

                    b.HasData(
                        new
                        {
                            Code = new Guid("05e32b18-149d-4af5-9e8a-eb630b250cf3"),
                            Name = "未婚",
                            Sort = 1,
                            Spell = "WH"
                        },
                        new
                        {
                            Code = new Guid("d533333e-8f04-40da-983e-eb4ec079eda2"),
                            Name = "已婚",
                            Sort = 2,
                            Spell = "YH"
                        },
                        new
                        {
                            Code = new Guid("eca1931a-e69a-4fda-9f5d-a2c4cfd7388e"),
                            Name = "丧偶",
                            Sort = 3,
                            Spell = "SO"
                        },
                        new
                        {
                            Code = new Guid("30b0e34d-cb46-4650-afad-5e8b5288ed05"),
                            Name = "离婚",
                            Sort = 4,
                            Spell = "LH"
                        },
                        new
                        {
                            Code = new Guid("6cca4dd0-8fa7-46be-90ab-f6ac0379adde"),
                            Name = "未说明的婚姻状况",
                            Sort = 5,
                            Spell = "WSMDHYZK,WYMDHYZK"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComNation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComNation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("ce17f92b-ee53-4aa6-8f3d-c3b13d865e2d"),
                            Name = "汉族",
                            Sort = 1,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("125af20a-05f2-4360-ad22-c31c96fee7d2"),
                            Name = "蒙古族",
                            Sort = 2,
                            Spell = "MGZ"
                        },
                        new
                        {
                            Code = new Guid("f6593d03-2150-4787-9eb7-56cfc6e42af6"),
                            Name = "回族",
                            Sort = 3,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("062054c0-596b-44e2-a474-95b212f3ed81"),
                            Name = "藏族",
                            Sort = 4,
                            Spell = "CZ,ZZ"
                        },
                        new
                        {
                            Code = new Guid("dee4d2f3-9aed-4a68-bbf3-3b822b3a975d"),
                            Name = "维吾尔族",
                            Sort = 5,
                            Spell = "WWEZ"
                        },
                        new
                        {
                            Code = new Guid("defb1d09-ea53-4851-847b-3d2384ecec02"),
                            Name = "苗族",
                            Sort = 6,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("cb36a1b6-82f7-4b56-8b6e-4ce9b3c090a8"),
                            Name = "彝族",
                            Sort = 7,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("f66dc976-43f3-48a5-9cbd-984a1e541a5d"),
                            Name = "壮族",
                            Sort = 8,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("a2b29557-6233-4f8e-955d-51f65d80c43e"),
                            Name = "布依族",
                            Sort = 9,
                            Spell = "BYZ"
                        },
                        new
                        {
                            Code = new Guid("0e6662af-45c6-4520-9fe1-bbaeecfb86a0"),
                            Name = "朝鲜族",
                            Sort = 10,
                            Spell = "CXZ,ZXZ"
                        },
                        new
                        {
                            Code = new Guid("0cff6174-5352-45ba-b473-e8af9c95c99b"),
                            Name = "满族",
                            Sort = 11,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("d05f6a47-6239-4771-899e-e6d1f792c5e6"),
                            Name = "侗族",
                            Sort = 12,
                            Spell = "DZ,TZ"
                        },
                        new
                        {
                            Code = new Guid("4beab6b5-7df2-447d-8484-455f3e99524d"),
                            Name = "瑶族",
                            Sort = 13,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("0e200734-36da-47c8-85fb-02b1c264abc4"),
                            Name = "白族",
                            Sort = 14,
                            Spell = "BZ"
                        },
                        new
                        {
                            Code = new Guid("a88f687c-f0f9-4f2d-93f9-db1d300f29d9"),
                            Name = "土家族",
                            Sort = 15,
                            Spell = "TGZ,TJZ"
                        },
                        new
                        {
                            Code = new Guid("e3096d33-71dc-4e7d-a6f8-31cdfd2b72d6"),
                            Name = "哈尼族",
                            Sort = 16,
                            Spell = "HNZ"
                        },
                        new
                        {
                            Code = new Guid("625d609f-05cd-4d99-9811-8b9eb3eb6459"),
                            Name = "哈萨克族",
                            Sort = 17,
                            Spell = "HSKZ"
                        },
                        new
                        {
                            Code = new Guid("782e08c8-1f74-4590-a97f-de6cfafe2b7f"),
                            Name = "傣族",
                            Sort = 18,
                            Spell = "DZ"
                        },
                        new
                        {
                            Code = new Guid("15d70dbf-78f6-4f28-97ed-30dcb9842e5d"),
                            Name = "黎族",
                            Sort = 19,
                            Spell = "LZ"
                        },
                        new
                        {
                            Code = new Guid("19f373ce-ffcf-4cf8-9aed-cc4bfc8180c6"),
                            Name = "傈僳族",
                            Sort = 20,
                            Spell = "LSZ"
                        },
                        new
                        {
                            Code = new Guid("1ba3efe3-2fdc-4a6a-95e3-dc9c06b59013"),
                            Name = "佤族",
                            Sort = 21,
                            Spell = "WZ"
                        },
                        new
                        {
                            Code = new Guid("220930b3-9705-497f-b06a-a2e563d6742a"),
                            Name = "畲族",
                            Sort = 22,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("2b191f90-2104-4414-b613-c679856a7433"),
                            Name = "高山族",
                            Sort = 23,
                            Spell = "GSZ"
                        },
                        new
                        {
                            Code = new Guid("a7ecfbb3-8be7-48a9-ac1f-6804d807a8cf"),
                            Name = "拉祜族",
                            Sort = 24,
                            Spell = "LHZ"
                        },
                        new
                        {
                            Code = new Guid("c5a44058-8b12-47a8-8295-5d1bd7f9983e"),
                            Name = "水族",
                            Sort = 25,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("8a4249e1-21b4-4bf8-a344-9910aaa596ad"),
                            Name = "东乡族",
                            Sort = 26,
                            Spell = "DXZ"
                        },
                        new
                        {
                            Code = new Guid("611b5190-58ed-4a98-901d-1d72d4dcf5e1"),
                            Name = "纳西族",
                            Sort = 27,
                            Spell = "NXZ"
                        },
                        new
                        {
                            Code = new Guid("3c4fa3f4-4e05-4712-b9cc-54d7d232dd6f"),
                            Name = "景颇族",
                            Sort = 28,
                            Spell = "JPZ"
                        },
                        new
                        {
                            Code = new Guid("ab4117fc-334e-4b6f-b6d0-08357ddc2ebe"),
                            Name = "柯尔克孜族",
                            Sort = 29,
                            Spell = "KEKZZ"
                        },
                        new
                        {
                            Code = new Guid("29e11f7b-a6f4-496d-ba53-74d81c4c771f"),
                            Name = "土族",
                            Sort = 30,
                            Spell = "TZ"
                        },
                        new
                        {
                            Code = new Guid("05730a1d-9803-4800-af3e-ad0973c20c37"),
                            Name = "达斡尔族",
                            Sort = 31,
                            Spell = "DWEZ"
                        },
                        new
                        {
                            Code = new Guid("d6b6fc5f-15df-459d-8e25-9199d073d306"),
                            Name = "仫佬族",
                            Sort = 32,
                            Spell = "MLZ"
                        },
                        new
                        {
                            Code = new Guid("60178d1c-62ab-4179-a367-f7ab18e3e709"),
                            Name = "羌族",
                            Sort = 33,
                            Spell = "QZ"
                        },
                        new
                        {
                            Code = new Guid("d50ebd1e-8a70-4db1-8abf-910567bfcf1f"),
                            Name = "布朗族",
                            Sort = 34,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("55198a23-15ee-493e-9715-3ca3ae0354dc"),
                            Name = "撒拉族",
                            Sort = 35,
                            Spell = "SLZ"
                        },
                        new
                        {
                            Code = new Guid("24fe8b69-bd16-4d75-922b-a4717644dff6"),
                            Name = "毛难族",
                            Sort = 36,
                            Spell = "MNZ"
                        },
                        new
                        {
                            Code = new Guid("775f88ae-a150-4a2e-a903-5b4cfcdfa830"),
                            Name = "仡佬族",
                            Sort = 37,
                            Spell = "GLZ,YLZ"
                        },
                        new
                        {
                            Code = new Guid("5886b1bd-23dd-46c8-8574-d036bcd53628"),
                            Name = "锡伯族",
                            Sort = 38,
                            Spell = "XBZ"
                        },
                        new
                        {
                            Code = new Guid("92769fcd-b0ba-42eb-b6f7-fd587c9bf914"),
                            Name = "阿昌族",
                            Sort = 39,
                            Spell = "ACZ,ECZ"
                        },
                        new
                        {
                            Code = new Guid("7c5d21e1-9a8a-4567-a022-9c54e185a18e"),
                            Name = "普米族",
                            Sort = 40,
                            Spell = "PMZ"
                        },
                        new
                        {
                            Code = new Guid("13ee562f-3089-479d-b5ef-d119b1a7db7e"),
                            Name = "塔吉克族",
                            Sort = 41,
                            Spell = "DJKZ,TJKZ"
                        },
                        new
                        {
                            Code = new Guid("eebc2c3b-de77-4752-b92a-ccce878f3e52"),
                            Name = "怒族",
                            Sort = 42,
                            Spell = "NZ"
                        },
                        new
                        {
                            Code = new Guid("bdbdb51f-fc2e-482c-a64d-6e77c1591fa2"),
                            Name = "乌孜别克族",
                            Sort = 43,
                            Spell = "WZBKZ"
                        },
                        new
                        {
                            Code = new Guid("2f24f752-c40a-4e5a-bb39-31e5e6aef999"),
                            Name = "俄罗斯族",
                            Sort = 44,
                            Spell = "ELSZ"
                        },
                        new
                        {
                            Code = new Guid("89d82a89-81b5-4e91-a990-ee7a1a8bdc50"),
                            Name = "鄂温克族",
                            Sort = 45,
                            Spell = "EWKZ"
                        },
                        new
                        {
                            Code = new Guid("e257e89c-3225-4e40-b080-0ffd55989b6a"),
                            Name = "崩龙族",
                            Sort = 46,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("b5fa4b2d-d54a-4af0-a3b6-eb2ad125fca6"),
                            Name = "保安族",
                            Sort = 47,
                            Spell = "BAZ"
                        },
                        new
                        {
                            Code = new Guid("4c7aa156-360e-441d-ade3-5c9a82bb0a30"),
                            Name = "裕固族",
                            Sort = 48,
                            Spell = "YGZ"
                        },
                        new
                        {
                            Code = new Guid("62686e0e-34c5-4f22-b0a7-f90cebb0f122"),
                            Name = "京族",
                            Sort = 49,
                            Spell = "JZ"
                        },
                        new
                        {
                            Code = new Guid("6b51952e-2322-4b0b-b767-5e9a9b3d02f9"),
                            Name = "塔塔尔族",
                            Sort = 50,
                            Spell = "DDEZ,TDEZ,DTEZ,TTEZ"
                        },
                        new
                        {
                            Code = new Guid("d541fc97-e8eb-4fbe-839a-666c279912b4"),
                            Name = "独龙族",
                            Sort = 51,
                            Spell = "DLZ"
                        },
                        new
                        {
                            Code = new Guid("17fd5fd9-4de9-4a4c-a7a9-14cf22e8ce6a"),
                            Name = "鄂伦春族",
                            Sort = 52,
                            Spell = "ELCZ"
                        },
                        new
                        {
                            Code = new Guid("10b0581e-c4a2-4d9e-8744-06b78a8c9add"),
                            Name = "赫哲族",
                            Sort = 53,
                            Spell = "HZZ"
                        },
                        new
                        {
                            Code = new Guid("01ff7f59-a876-4ac6-a30e-8a46f59f9e2d"),
                            Name = "门巴族",
                            Sort = 54,
                            Spell = "MBZ"
                        },
                        new
                        {
                            Code = new Guid("a6eb49de-3d3b-4426-9638-5d5c292afdd6"),
                            Name = "珞巴族",
                            Sort = 55,
                            Spell = "LBZ"
                        },
                        new
                        {
                            Code = new Guid("e435c530-8292-46c8-b98b-757f7f7f8586"),
                            Name = "基诺族",
                            Sort = 56,
                            Spell = "JNZ"
                        },
                        new
                        {
                            Code = new Guid("f720f863-85c8-47d4-9a17-7b146795bd1f"),
                            Name = "其他",
                            Sort = 57,
                            Spell = "JT,QT"
                        },
                        new
                        {
                            Code = new Guid("ce4c48d9-be64-4a73-8f85-ef03b5fdf1f6"),
                            Name = "外国血统中国人士",
                            Sort = 58,
                            Spell = "WGXTZGRS"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComPolitical", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComPolitical");

                    b.HasData(
                        new
                        {
                            Code = new Guid("5a10dcca-f743-48d4-bd71-dcc8cbc4b251"),
                            Name = "中共党员",
                            Sort = 1,
                            Spell = "ZGDY"
                        },
                        new
                        {
                            Code = new Guid("920420a9-ebe1-4774-8730-f32466267138"),
                            Name = "中共预备党员",
                            Sort = 2,
                            Spell = "ZGYBDY"
                        },
                        new
                        {
                            Code = new Guid("356af1cb-7437-4dfd-894f-dd4f1b911746"),
                            Name = "共青团员",
                            Sort = 3,
                            Spell = "GQTY"
                        },
                        new
                        {
                            Code = new Guid("3704f305-4a12-429a-90c5-d8a26cadac87"),
                            Name = "民革党员",
                            Sort = 4,
                            Spell = "MGDY,MJDY"
                        },
                        new
                        {
                            Code = new Guid("435e8a81-e243-443d-8cff-d2fdf71f6470"),
                            Name = "民盟盟员",
                            Sort = 5,
                            Spell = "MMMY"
                        },
                        new
                        {
                            Code = new Guid("bb71467f-d418-4722-9d73-81ef8a457dbc"),
                            Name = "民建会员",
                            Sort = 6,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("312a1908-831c-44db-bd24-1ef37d1b3fbe"),
                            Name = "民进会员",
                            Sort = 7,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("8b60d9d8-a225-4043-a0dc-9ef3d6ccb029"),
                            Name = "农工党党员",
                            Sort = 8,
                            Spell = "NGDDY"
                        },
                        new
                        {
                            Code = new Guid("8525cba8-9d54-44ec-b3ac-584bc35e7b11"),
                            Name = "致公党党员",
                            Sort = 9,
                            Spell = "ZGDDY"
                        },
                        new
                        {
                            Code = new Guid("a1cf9baa-4949-4121-9e9f-b90dcd5aa19b"),
                            Name = "九三学社社员",
                            Sort = 10,
                            Spell = "JSXSSY"
                        },
                        new
                        {
                            Code = new Guid("cccce48d-4daf-4fae-b51c-aaa4f232c26e"),
                            Name = "台盟盟员",
                            Sort = 11,
                            Spell = "TMMY"
                        },
                        new
                        {
                            Code = new Guid("6bf1c928-f204-4ebb-9d0a-9736df99e925"),
                            Name = "无党派人士",
                            Sort = 12,
                            Spell = "MDPRS,WDPRS"
                        },
                        new
                        {
                            Code = new Guid("8e871348-b291-44e3-9aff-534cfe8eb4cf"),
                            Name = "群众",
                            Sort = 13,
                            Spell = "QZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComPost", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComPost");

                    b.HasData(
                        new
                        {
                            Code = new Guid("442c036f-dde7-4ab0-aad7-f4a4afd7465a"),
                            Name = "卫",
                            Sort = 1,
                            Spell = "W"
                        },
                        new
                        {
                            Code = new Guid("4dbe8911-71ed-4fde-a92f-a1310a8bb666"),
                            Name = "工",
                            Sort = 2,
                            Spell = "G"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("LevelCode");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("LevelCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("ComProfessionTitle");

                    b.HasData(
                        new
                        {
                            Code = new Guid("ee1acec5-5b8c-471d-8e4c-1797963916e7"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任医师",
                            Sort = 1,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("4e3829f6-bb73-4c4c-9e5a-08e771953dd8"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任药师",
                            Sort = 2,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("40eae5b7-5c3f-47c5-a09b-9f71e769a970"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任护师",
                            Sort = 3,
                            Spell = "ZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("61d7e0cd-64a6-4c44-b5c2-181bdd959e6f"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任技师",
                            Sort = 4,
                            Spell = "ZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("62c7eb06-8777-4d1c-9ce1-fd398319d4ac"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任医师",
                            Sort = 5,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("a10b7876-e124-4a14-a90b-89639b526e3f"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任药师",
                            Sort = 6,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("6b629ee5-d216-448a-9105-01ffac4432f3"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任护师",
                            Sort = 7,
                            Spell = "FZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("2ae101cc-4bec-4280-9181-978316e67c5f"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任技师",
                            Sort = 8,
                            Spell = "FZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("e262551c-8165-4fff-83f6-127e0040ee1a"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主治医师",
                            Sort = 9,
                            Spell = "ZZYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("e27a4041-6227-4855-a6d6-caf3e2b13b35"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管药师",
                            Sort = 10,
                            Spell = "ZGYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("75bbcc1d-8a84-4260-9371-a958bf33aa17"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管护师",
                            Sort = 11,
                            Spell = "ZGHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("8adaf683-4cf9-4a95-8dba-8634025ef9ce"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管技师",
                            Sort = 12,
                            Spell = "ZGJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("00a15d5b-bddd-40e2-8aa5-70b81ff3928e"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医师",
                            Sort = 13,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("4f0e992c-b892-424e-a877-0674cad71fa6"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医士",
                            Sort = 14,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("d14d09f9-acc3-4f70-aa34-7379565c13a2"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药师",
                            Sort = 15,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("7a2ec004-23f3-4123-abd8-831ada164952"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药士",
                            Sort = 16,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("c230efa5-8c4a-44ad-a615-3b1727de19a5"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护师",
                            Sort = 17,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("4b4e962c-0526-4a20-9ca9-93171b5715ba"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护士",
                            Sort = 18,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("32a5a6b9-584c-4b2b-8c3f-105c653f5270"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技师",
                            Sort = 19,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("91e11499-5250-4bf1-bf24-988f2e223c4c"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技士",
                            Sort = 20,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("59393e25-fe3d-453d-9622-d5d705c9fa74"),
                            LevelCode = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无职称",
                            Sort = 21,
                            Spell = "MZC,WZC",
                            TypeCode = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleLevel");

                    b.HasData(
                        new
                        {
                            Code = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "正高级",
                            Sort = 1,
                            Spell = "ZGJ"
                        },
                        new
                        {
                            Code = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副高级",
                            Sort = 2,
                            Spell = "FGJ"
                        },
                        new
                        {
                            Code = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "中级",
                            Sort = 3,
                            Spell = "ZJ"
                        },
                        new
                        {
                            Code = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "初级",
                            Sort = 4,
                            Spell = "CJ"
                        },
                        new
                        {
                            Code = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768"),
                            Name = "卫生技术人员",
                            Sort = 1,
                            Spell = "WSJSRY,WSJZRY"
                        },
                        new
                        {
                            Code = new Guid("ea7c2801-ee7e-469e-a855-1347c9c96b53"),
                            Name = "高等学校教师",
                            Sort = 2,
                            Spell = "GDXJJS,GDXXJS"
                        },
                        new
                        {
                            Code = new Guid("abf1a772-09df-4c65-a5f9-0ceffd085579"),
                            Name = "中等专业学校教师",
                            Sort = 3,
                            Spell = "ZDZYXJJS,ZDZYXXJS"
                        },
                        new
                        {
                            Code = new Guid("80b25d97-2e02-4c7a-8f23-c7cf496037df"),
                            Name = "技工学校教师",
                            Sort = 4,
                            Spell = "JGXJJS,JGXXJS"
                        },
                        new
                        {
                            Code = new Guid("b2637983-d85e-40d5-8001-cccd4601601f"),
                            Name = "中学教师",
                            Sort = 5,
                            Spell = "ZXJS"
                        },
                        new
                        {
                            Code = new Guid("19b2a7e9-aabd-4f8f-8d9d-5de08ab2e91d"),
                            Name = "小学（幼儿园）教师",
                            Sort = 6,
                            Spell = "XX（YEY）JS"
                        },
                        new
                        {
                            Code = new Guid("a7c631a5-e308-42b3-9472-97140b783e6d"),
                            Name = "自然科学研究人员",
                            Sort = 7,
                            Spell = "ZRKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("4a9aa7fe-1ec1-49c7-9682-c483a2366d69"),
                            Name = "社会科学研究人员",
                            Sort = 8,
                            Spell = "SHKXYJRY,SKKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("a2505535-f75a-48cc-9d25-076400111441"),
                            Name = "工程技术人员",
                            Sort = 9,
                            Spell = "GCJSRY,GCJZRY"
                        },
                        new
                        {
                            Code = new Guid("96e0f964-0861-453f-94f8-e48efbad732f"),
                            Name = "实验技术人员",
                            Sort = 10,
                            Spell = "SYJSRY,SYJZRY"
                        },
                        new
                        {
                            Code = new Guid("2b5b9b5a-5748-417f-a5db-e3217cb64fea"),
                            Name = "农业技术人员",
                            Sort = 11,
                            Spell = "NYJSRY,NYJZRY"
                        },
                        new
                        {
                            Code = new Guid("ef1df2b7-f9dc-4ae9-87c7-daa2113b8a48"),
                            Name = "经济专业人员",
                            Sort = 12,
                            Spell = "JJZYRY"
                        },
                        new
                        {
                            Code = new Guid("fb66f9c4-35ae-4408-8bc8-189abacc26d1"),
                            Name = "会计专业人员",
                            Sort = 13,
                            Spell = "HJZYRY,KJZYRY"
                        },
                        new
                        {
                            Code = new Guid("23c98c0f-a6a1-4f7b-89e3-c2ec3c242a4b"),
                            Name = "审计专业人员",
                            Sort = 14,
                            Spell = "SJZYRY"
                        },
                        new
                        {
                            Code = new Guid("51b700cf-bad3-4ff2-8a98-0678ccd1521d"),
                            Name = "统计专业人员",
                            Sort = 15,
                            Spell = "TJZYRY"
                        },
                        new
                        {
                            Code = new Guid("0dfdd501-a202-48ed-ab7a-de986748153d"),
                            Name = "新闻专业人员",
                            Sort = 16,
                            Spell = "XWZYRY"
                        },
                        new
                        {
                            Code = new Guid("864f3319-7dfe-4b67-91d0-99457407b804"),
                            Name = "出版专业人员",
                            Sort = 17,
                            Spell = "CBZYRY"
                        },
                        new
                        {
                            Code = new Guid("9403ce46-e0a2-4a6a-95ff-9c3cca15ab50"),
                            Name = "图书资料专业人员",
                            Sort = 18,
                            Spell = "TSZLZYRY"
                        },
                        new
                        {
                            Code = new Guid("3919e6a1-ffa8-4d29-ac7a-cb746faaea8e"),
                            Name = "文物博物专业人员",
                            Sort = 19,
                            Spell = "WWBWZYRY"
                        },
                        new
                        {
                            Code = new Guid("596592e1-67e4-48f9-99c9-47dce1c9f342"),
                            Name = "档案专业人员",
                            Sort = 20,
                            Spell = "DAZYRY"
                        },
                        new
                        {
                            Code = new Guid("c3cd2ac4-52c1-4129-9f68-5d3a876efaab"),
                            Name = "广播电视播音人员",
                            Sort = 21,
                            Spell = "ABDSBYRY,GBDSBYRY"
                        },
                        new
                        {
                            Code = new Guid("2f1eec53-cbf6-4c9d-b909-533d2d8ddc66"),
                            Name = "翻译人员",
                            Sort = 22,
                            Spell = "FYRY"
                        },
                        new
                        {
                            Code = new Guid("4349d50f-971f-48d0-82bd-e7ce6d92a06f"),
                            Name = "律师",
                            Sort = 23,
                            Spell = "LS"
                        },
                        new
                        {
                            Code = new Guid("46977799-a117-4544-a8af-00252ac42c38"),
                            Name = "公证员",
                            Sort = 24,
                            Spell = "GZY"
                        },
                        new
                        {
                            Code = new Guid("ee7b36e7-6123-44d7-aad5-ad90f8d52af7"),
                            Name = "海关人员",
                            Sort = 25,
                            Spell = "HGRY"
                        },
                        new
                        {
                            Code = new Guid("b2e7614f-f9a1-43b8-a704-50ff24dd6815"),
                            Name = "船舶技术人员",
                            Sort = 26,
                            Spell = "CBJSRY,CBJZRY"
                        },
                        new
                        {
                            Code = new Guid("30df1e4d-4641-432f-b0d1-f265f243afaf"),
                            Name = "民用航空飞行技术人员",
                            Sort = 27,
                            Spell = "MYHKFHJSRY,MYHKFXJSRY,MYHKFHJZRY,MYHKFXJZRY"
                        },
                        new
                        {
                            Code = new Guid("5b451f50-8197-4c9a-9106-6e48a346a6ca"),
                            Name = "艺术专业人员",
                            Sort = 28,
                            Spell = "YSZYRY,YZZYRY"
                        },
                        new
                        {
                            Code = new Guid("87fae6a8-276a-40e2-a12e-62e3aa0909e0"),
                            Name = "工艺美术专业人员",
                            Sort = 29,
                            Spell = "GYMSZYRY,GYMZZYRY"
                        },
                        new
                        {
                            Code = new Guid("95c3e533-1d6b-407d-9247-5e7f62be6c55"),
                            Name = "体育教练员",
                            Sort = 30,
                            Spell = "TYJLY"
                        },
                        new
                        {
                            Code = new Guid("4a101a72-bd30-4eca-ae31-fb5531258e6d"),
                            Name = "思想政治工作人员",
                            Sort = 31,
                            Spell = "SXZZGZRY"
                        },
                        new
                        {
                            Code = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c"),
                            Name = "无",
                            Sort = 32,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysDept", b =>
                {
                    b.Property<string>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("DeptName")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("DeptCode");

                    b.ToTable("SysDept");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.Property<string>("EmpCode")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdminDutyCode");

                    b.Property<int>("Age");

                    b.Property<string>("ArchivesNo");

                    b.Property<string>("BankCard");

                    b.Property<DateTime>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ComPostCode");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateEmp");

                    b.Property<Guid?>("DegreeCode");

                    b.Property<string>("DeptCode")
                        .IsRequired();

                    b.Property<Guid?>("EducationCode");

                    b.Property<DateTime?>("EducationDate");

                    b.Property<string>("EmpName")
                        .IsRequired();

                    b.Property<Guid>("GenderCode");

                    b.Property<DateTime?>("GraduationDate");

                    b.Property<string>("HomeAdd");

                    b.Property<int>("HospitalAge");

                    b.Property<DateTime>("HospitalDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IdentityAdd");

                    b.Property<string>("IdentityCard")
                        .IsRequired();

                    b.Property<bool>("IsPost")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStop")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MarriageCode");

                    b.Property<Guid>("NationCode");

                    b.Property<string>("NativePlace");

                    b.Property<string>("OldName");

                    b.Property<string>("OpenBank");

                    b.Property<string>("Photo");

                    b.Property<Guid>("PoliticalCode");

                    b.Property<DateTime?>("PoliticalDate");

                    b.Property<Guid>("PostCode");

                    b.Property<string>("Practice");

                    b.Property<DateTime?>("PracticeDate");

                    b.Property<Guid?>("ProfessionTitleCode");

                    b.Property<Guid?>("ProfessionTitleLevelCode");

                    b.Property<Guid?>("ProfessionTitleTypeCode");

                    b.Property<string>("PublicMoneyNo");

                    b.Property<string>("Remark");

                    b.Property<string>("School");

                    b.Property<string>("SchoolMajor");

                    b.Property<string>("SocialInsuranceNo");

                    b.Property<string>("Spell");

                    b.Property<string>("Telephone");

                    b.Property<Guid?>("TypeCode");

                    b.Property<int>("WorkAge");

                    b.Property<DateTime?>("WorkDate");

                    b.HasKey("EmpCode");

                    b.HasIndex("AdminDutyCode");

                    b.HasIndex("ComPostCode");

                    b.HasIndex("DegreeCode");

                    b.HasIndex("DeptCode");

                    b.HasIndex("EducationCode");

                    b.HasIndex("GenderCode");

                    b.HasIndex("MarriageCode");

                    b.HasIndex("NationCode");

                    b.HasIndex("PoliticalCode");

                    b.HasIndex("ProfessionTitleCode");

                    b.HasIndex("ProfessionTitleLevelCode");

                    b.HasIndex("ProfessionTitleTypeCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysEmp");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmpType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysEmpType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("2db865be-6fc2-4344-99cf-30534802f170"),
                            Name = "在编人员",
                            Sort = 1,
                            Spell = "ZBRY"
                        },
                        new
                        {
                            Code = new Guid("6013b422-70d0-4a2b-9e82-c11586ad91d7"),
                            Name = "人事代理",
                            Sort = 2,
                            Spell = "RSDL"
                        },
                        new
                        {
                            Code = new Guid("b032326b-d74e-4110-a11b-6ffa4615c176"),
                            Name = "临时人员",
                            Sort = 3,
                            Spell = "LSRY"
                        },
                        new
                        {
                            Code = new Guid("da23319b-0599-4047-8d80-482ac0322b85"),
                            Name = "离退人员",
                            Sort = 4,
                            Spell = "LTRY"
                        },
                        new
                        {
                            Code = new Guid("4b4201f4-c153-43ce-9c66-f794b61c9269"),
                            Name = "辞职人员",
                            Sort = 5,
                            Spell = "CZRY"
                        },
                        new
                        {
                            Code = new Guid("fc8a773c-43f2-4550-8f20-c838b7dd885c"),
                            Name = "返聘人员",
                            Sort = 6,
                            Spell = "FPRY"
                        },
                        new
                        {
                            Code = new Guid("a6eaaf89-2f3a-4769-83f7-201f7e1bae1b"),
                            Name = "调出人员",
                            Sort = 7,
                            Spell = "DCRY,TCRY"
                        },
                        new
                        {
                            Code = new Guid("618d9c01-6d8d-40dc-967e-fbcc5d3259d0"),
                            Name = "除名人员",
                            Sort = 8,
                            Spell = "CMRY"
                        },
                        new
                        {
                            Code = new Guid("069c64bc-5f51-41f5-a179-a3a962ba4696"),
                            Name = "实习进修",
                            Sort = 9,
                            Spell = "SXJX"
                        },
                        new
                        {
                            Code = new Guid("8bf4450e-107e-4893-869c-17940436f60b"),
                            Name = "借出人员",
                            Sort = 10,
                            Spell = "JCRY"
                        },
                        new
                        {
                            Code = new Guid("e068a839-f8c6-4962-a1ec-c58eac9ea4db"),
                            Name = "长期出国人员",
                            Sort = 11,
                            Spell = "CJCGRY,ZJCGRY,CQCGRY,ZQCGRY"
                        },
                        new
                        {
                            Code = new Guid("4a93a926-639c-4b0c-a4ad-a5d09399a856"),
                            Name = "自动离职人员",
                            Sort = 12,
                            Spell = "ZDLZRY"
                        },
                        new
                        {
                            Code = new Guid("8e086618-e889-4b39-9ef9-098b18aaa572"),
                            Name = "停薪留职人员",
                            Sort = 13,
                            Spell = "TXLZRY"
                        },
                        new
                        {
                            Code = new Guid("3442e56b-a348-468d-9bce-82d3288c8351"),
                            Name = "编外离岗人员",
                            Sort = 14,
                            Spell = "BWLGRY"
                        },
                        new
                        {
                            Code = new Guid("4a8f584c-7be1-46cd-885f-4abd41f95732"),
                            Name = "内部退养",
                            Sort = 15,
                            Spell = "NBTY"
                        },
                        new
                        {
                            Code = new Guid("440ad1b9-4aa1-4c4f-a42b-00fd4b072323"),
                            Name = "试用人员",
                            Sort = 16,
                            Spell = "SYRY"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Action");

                    b.Property<string>("Controller");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysNavbar");

                    b.HasData(
                        new
                        {
                            Code = new Guid("baefe4fd-ce7c-4374-b855-d3a93218706f"),
                            Action = "Index",
                            Controller = "SysNavbarType",
                            Name = "菜单类别",
                            Sort = 1,
                            Spell = "CCLB,CDLB,CSLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("b0ed1bce-a2bb-4ae5-87b0-2974d74827ea"),
                            Action = "Index",
                            Controller = "SysNavbar",
                            Name = "菜单",
                            Sort = 2,
                            Spell = "CC,CD,CS",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("9fe533d0-5c2f-4487-9377-d7f6eec54b10"),
                            Action = "Index",
                            Controller = "ComGender",
                            Name = "性别",
                            Sort = 3,
                            Spell = "XB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("0e7f78fd-0db7-4326-9c08-dd34f9337b07"),
                            Action = "Index",
                            Controller = "ComNation",
                            Name = "民族",
                            Sort = 4,
                            Spell = "MZ",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("0f43f0a8-e6e8-4185-95ab-eb5654fa649e"),
                            Action = "Index",
                            Controller = "ComPolitical",
                            Name = "政治面貌",
                            Sort = 5,
                            Spell = "ZZMM",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("76d6d639-ad17-475e-837a-8dcaee0e2e9f"),
                            Action = "Index",
                            Controller = "ComProfessionTitleType",
                            Name = "职称系列",
                            Sort = 6,
                            Spell = "ZCJL,ZCXL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("181700bc-bcf3-4082-824a-c549ea404ea1"),
                            Action = "Index",
                            Controller = "ComProfessionTitleLevel",
                            Name = "职称级别",
                            Sort = 7,
                            Spell = "ZCJB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("93943266-8562-43e4-a3b0-3d21763b805a"),
                            Action = "Index",
                            Controller = "ComProfessionTitle",
                            Name = "职称",
                            Sort = 8,
                            Spell = "ZC",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("2e4f408f-3760-4529-9e32-05e1bc061493"),
                            Action = "Index",
                            Controller = "ComAdminDuty",
                            Name = "行政职务",
                            Sort = 9,
                            Spell = "HZZW,XZZW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("a86cc36a-a851-4234-bc8d-6531fc6ffb75"),
                            Action = "Index",
                            Controller = "SysEmpType",
                            Name = "人员类别",
                            Sort = 10,
                            Spell = "RYLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("d8759034-211a-4b4b-9161-da7286716550"),
                            Action = "Index",
                            Controller = "ComEducation",
                            Name = "学历",
                            Sort = 11,
                            Spell = "XL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("d678a468-0582-4362-a5cc-acf9988168c3"),
                            Action = "Index",
                            Controller = "ComDegree",
                            Name = "学位",
                            Sort = 12,
                            Spell = "XW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("46671bea-8417-4981-bac2-b81ced5bd8a8"),
                            Action = "Index",
                            Controller = "ComMarriage",
                            Name = "婚姻状况",
                            Sort = 13,
                            Spell = "HYZK",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("ce67b524-3f64-4bfc-9b62-a28cc4fbc787"),
                            Action = "Index",
                            Controller = "SysDept",
                            Name = "科室信息",
                            Sort = 14,
                            Spell = "KSXX",
                            TypeCode = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e")
                        },
                        new
                        {
                            Code = new Guid("015bea5f-35c3-4d5e-b1bd-d703c822607b"),
                            Action = "Index",
                            Controller = "SysEmp",
                            Name = "人员管理",
                            Sort = 15,
                            Spell = "RYGL",
                            TypeCode = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbarType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysNavbarType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc"),
                            Name = "基础数据维护",
                            Sort = 1,
                            Spell = "JCSJWH"
                        },
                        new
                        {
                            Code = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e"),
                            Name = "机构管理",
                            Sort = 2,
                            Spell = "JGGL"
                        },
                        new
                        {
                            Code = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993"),
                            Name = "人事档案",
                            Sort = 3,
                            Spell = "RSDA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("LevelCode")
                        .HasConstraintName("FK_LevelCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComAdminDuty", "ComAdminDuty")
                        .WithMany("SysEmps")
                        .HasForeignKey("AdminDutyCode")
                        .HasConstraintName("FK_AdminDutyCode_ComAdminDuty_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComPost", "ComPost")
                        .WithMany("SysEmps")
                        .HasForeignKey("ComPostCode");

                    b.HasOne("HospitalPersonnelSystem.Models.ComDegree", "ComDegree")
                        .WithMany("SysEmps")
                        .HasForeignKey("DegreeCode")
                        .HasConstraintName("FK_DegreeCode_ComDegree_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysDept", "SysDept")
                        .WithMany("SysEmps")
                        .HasForeignKey("DeptCode")
                        .HasConstraintName("FK_DeptCode_SysDept_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComEducation", "ComEducation")
                        .WithMany("SysEmps")
                        .HasForeignKey("EducationCode")
                        .HasConstraintName("FK_EducationCode_ComEducation_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComGender", "ComGender")
                        .WithMany("SysEmps")
                        .HasForeignKey("GenderCode")
                        .HasConstraintName("FK_GenderCode_ComGender_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComMarriage", "ComMarriage")
                        .WithMany("SysEmps")
                        .HasForeignKey("MarriageCode")
                        .HasConstraintName("FK_MarriageCode_ComMarriage_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComNation", "ComNation")
                        .WithMany("SysEmps")
                        .HasForeignKey("NationCode")
                        .HasConstraintName("FK_NationCode_ComNation_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComPolitical", "ComPolitical")
                        .WithMany("SysEmps")
                        .HasForeignKey("PoliticalCode")
                        .HasConstraintName("FK_PoliticalCode_ComPolitical_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitle", "ComProfessionTitle")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleCode")
                        .HasConstraintName("FK_PTCode_ComProfessionTitle_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleLevelCode")
                        .HasConstraintName("FK_PTLCode_ComProfessionTitleLevel_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleTypeCode")
                        .HasConstraintName("FK_PTTCode_ComProfessionTitleType_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysEmpType", "SysEmpType")
                        .WithMany("SysEmps")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysEmpType_SysEmp");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.SysNavbarType", "SysNavbarType")
                        .WithMany("SysNavbars")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysNavbarType_SysNavbar")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
