// <auto-generated />
using System;
using HospitalPersonnelSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalPersonnelSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComAdminDuty", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComAdminDuty");

                    b.HasData(
                        new
                        {
                            Code = new Guid("bb34f157-6cdf-4d9f-a850-780801500942"),
                            Name = "院长",
                            Sort = 1,
                            Spell = "YC,YZ"
                        },
                        new
                        {
                            Code = new Guid("140064e5-adb0-4b51-930c-98f0a689ef34"),
                            Name = "副院长",
                            Sort = 2,
                            Spell = "FYC,FYZ"
                        },
                        new
                        {
                            Code = new Guid("6f66db6f-4315-434a-a9eb-49d38aea1d55"),
                            Name = "书记",
                            Sort = 3,
                            Spell = "SJ"
                        },
                        new
                        {
                            Code = new Guid("b543b9a0-4b67-412b-88d4-954f2e642346"),
                            Name = "副书记",
                            Sort = 4,
                            Spell = "FSJ"
                        },
                        new
                        {
                            Code = new Guid("c2633dff-8499-4809-9e95-b1296159e523"),
                            Name = "团委书记",
                            Sort = 5,
                            Spell = "TWSJ"
                        },
                        new
                        {
                            Code = new Guid("a03f376f-c6e1-4bd6-90e6-ae28c9c0964f"),
                            Name = "团委副书记",
                            Sort = 6,
                            Spell = "TWFSJ"
                        },
                        new
                        {
                            Code = new Guid("7eab3162-aaed-43b1-ad0d-d32b3599ac97"),
                            Name = "大科主任",
                            Sort = 7,
                            Spell = "DKZR"
                        },
                        new
                        {
                            Code = new Guid("26852689-2cf4-4fe4-b7ee-16b1f06d28cc"),
                            Name = "科主任",
                            Sort = 8,
                            Spell = "KZR"
                        },
                        new
                        {
                            Code = new Guid("f12f7f92-3365-43ca-be3d-f90cc2dc785b"),
                            Name = "副主任",
                            Sort = 9,
                            Spell = "FZR"
                        },
                        new
                        {
                            Code = new Guid("e9f4e130-aeed-4c4e-a9a9-5c5832d8dcc1"),
                            Name = "护士长",
                            Sort = 10,
                            Spell = "HSC,HSZ"
                        },
                        new
                        {
                            Code = new Guid("b2fddfb4-0040-4dfe-9f3b-e693b4d8e093"),
                            Name = "副护士长",
                            Sort = 11,
                            Spell = "FHSC,FHSZ"
                        },
                        new
                        {
                            Code = new Guid("b9676ec1-03a2-4879-86c2-4b28f04bb1b2"),
                            Name = "科员",
                            Sort = 12,
                            Spell = "KY"
                        },
                        new
                        {
                            Code = new Guid("33e214f5-7235-462b-9ab2-4f573ec0d7d3"),
                            Name = "干事",
                            Sort = 13,
                            Spell = "GS"
                        },
                        new
                        {
                            Code = new Guid("96038ac0-39db-4202-b8ee-361485f215b1"),
                            Name = "返聘",
                            Sort = 14,
                            Spell = "FP"
                        },
                        new
                        {
                            Code = new Guid("40574e21-beb0-47fd-a754-143abb0a85dd"),
                            Name = "无",
                            Sort = 15,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComDegree", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComDegree");

                    b.HasData(
                        new
                        {
                            Code = new Guid("a348b5a6-a6d2-4edf-9282-cb818f72de2d"),
                            Name = "博士后",
                            Sort = 1,
                            Spell = "BSH"
                        },
                        new
                        {
                            Code = new Guid("833045e2-bc21-4a5a-98cd-159892401293"),
                            Name = "博士",
                            Sort = 2,
                            Spell = "BS"
                        },
                        new
                        {
                            Code = new Guid("c9652c38-a7a4-485b-ba65-0d20331faa09"),
                            Name = "硕士",
                            Sort = 3,
                            Spell = "SS"
                        },
                        new
                        {
                            Code = new Guid("41e0d5f3-40f0-421f-ae06-bf7cc2acfb97"),
                            Name = "学士",
                            Sort = 4,
                            Spell = "XS"
                        },
                        new
                        {
                            Code = new Guid("3002aa36-f309-47a5-a170-42f89f92ffc0"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComEducation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComEducation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("61fbbb24-931f-4af8-b334-8d6ccf238e1a"),
                            Name = "博士研究生",
                            Sort = 1,
                            Spell = "BSYJS"
                        },
                        new
                        {
                            Code = new Guid("5dcc9704-28e1-44f4-a1bd-50f3651d7611"),
                            Name = "硕士研究生",
                            Sort = 2,
                            Spell = "SSYJS"
                        },
                        new
                        {
                            Code = new Guid("32f8c1b7-5951-4d9d-9752-c52a8061fafb"),
                            Name = "本科",
                            Sort = 3,
                            Spell = "BK"
                        },
                        new
                        {
                            Code = new Guid("3ec66f80-c869-40c2-a8b1-68c3806d5de7"),
                            Name = "专科",
                            Sort = 4,
                            Spell = "ZK"
                        },
                        new
                        {
                            Code = new Guid("d2c2d95a-70ac-462d-8332-69416dd81dfd"),
                            Name = "中专",
                            Sort = 5,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("a4178c88-4b84-4268-a91d-78272eab8f56"),
                            Name = "高中及以下",
                            Sort = 6,
                            Spell = "GZJYX"
                        },
                        new
                        {
                            Code = new Guid("c3b13918-19c0-4e62-9996-3a5820e76062"),
                            Name = "技校",
                            Sort = 7,
                            Spell = "JJ,JX"
                        },
                        new
                        {
                            Code = new Guid("f790ef85-6ab6-4d50-a568-d284ba2e11f7"),
                            Name = "其他",
                            Sort = 8,
                            Spell = "JT,QT"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComGender", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComGender");

                    b.HasData(
                        new
                        {
                            Code = new Guid("e938b3d7-2153-4e3e-a235-da966f9cdcea"),
                            Name = "男",
                            Sort = 1,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("58e3d735-d6f1-4b2e-8898-5c4183e3bc81"),
                            Name = "女",
                            Sort = 2,
                            Spell = "N"
                        },
                        new
                        {
                            Code = new Guid("f1384219-82c1-47d8-8689-0be7c7f41129"),
                            Name = "未知",
                            Sort = 3,
                            Spell = "WZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComMarriage", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComMarriage");

                    b.HasData(
                        new
                        {
                            Code = new Guid("224f2032-2a28-46ed-a69d-3fba3061398b"),
                            Name = "未婚",
                            Sort = 1,
                            Spell = "WH"
                        },
                        new
                        {
                            Code = new Guid("76561c35-0a22-4c4e-8973-304f30490b0b"),
                            Name = "已婚",
                            Sort = 2,
                            Spell = "YH"
                        },
                        new
                        {
                            Code = new Guid("dd504b02-d62d-4c93-bd92-0ced1a6ae345"),
                            Name = "丧偶",
                            Sort = 3,
                            Spell = "SO"
                        },
                        new
                        {
                            Code = new Guid("b98fcc64-5af9-4bae-96d3-5b3b91faec43"),
                            Name = "离婚",
                            Sort = 4,
                            Spell = "LH"
                        },
                        new
                        {
                            Code = new Guid("6cca4dd0-8fa7-46be-90ab-f6ac0379adde"),
                            Name = "未说明的婚姻状况",
                            Sort = 5,
                            Spell = "WSMDHYZK,WYMDHYZK"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComNation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComNation");

                    b.HasData(
                        new
                        {
                            Code = new Guid("ce17f92b-ee53-4aa6-8f3d-c3b13d865e2d"),
                            Name = "汉族",
                            Sort = 1,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("8ffb4df6-a4a8-49fd-855d-6965910b83a5"),
                            Name = "蒙古族",
                            Sort = 2,
                            Spell = "MGZ"
                        },
                        new
                        {
                            Code = new Guid("48d44109-0140-4797-a01c-7ff1a3c0bcd4"),
                            Name = "回族",
                            Sort = 3,
                            Spell = "HZ"
                        },
                        new
                        {
                            Code = new Guid("a0318f52-d049-414e-a997-a7d15605c70f"),
                            Name = "藏族",
                            Sort = 4,
                            Spell = "CZ,ZZ"
                        },
                        new
                        {
                            Code = new Guid("fe07f3ba-26be-47db-b5a9-0fef14f552f4"),
                            Name = "维吾尔族",
                            Sort = 5,
                            Spell = "WWEZ"
                        },
                        new
                        {
                            Code = new Guid("324ba6c7-17c8-4b14-a6b0-be3d2e33fa46"),
                            Name = "苗族",
                            Sort = 6,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("15547824-c1b9-47b2-afc2-05df11c42e82"),
                            Name = "彝族",
                            Sort = 7,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("7bea4600-d252-4ee1-b140-8a65280defce"),
                            Name = "壮族",
                            Sort = 8,
                            Spell = "ZZ"
                        },
                        new
                        {
                            Code = new Guid("07a34931-c620-4371-8c5f-7b67fc219349"),
                            Name = "布依族",
                            Sort = 9,
                            Spell = "BYZ"
                        },
                        new
                        {
                            Code = new Guid("8cda4901-bfef-4a5c-ab96-46f4f2705271"),
                            Name = "朝鲜族",
                            Sort = 10,
                            Spell = "CXZ,ZXZ"
                        },
                        new
                        {
                            Code = new Guid("f0fdc89f-d89a-4ab9-a298-45d7aad50de6"),
                            Name = "满族",
                            Sort = 11,
                            Spell = "MZ"
                        },
                        new
                        {
                            Code = new Guid("0346d526-1a85-4074-8825-52de415ceffe"),
                            Name = "侗族",
                            Sort = 12,
                            Spell = "DZ,TZ"
                        },
                        new
                        {
                            Code = new Guid("e00f72e6-b7f2-499e-ae90-b8f046f0389b"),
                            Name = "瑶族",
                            Sort = 13,
                            Spell = "YZ"
                        },
                        new
                        {
                            Code = new Guid("6f15051a-a852-4bfb-bca6-48e29a3003cc"),
                            Name = "白族",
                            Sort = 14,
                            Spell = "BZ"
                        },
                        new
                        {
                            Code = new Guid("abc5634f-648e-42f6-9b1c-c35536dbec72"),
                            Name = "土家族",
                            Sort = 15,
                            Spell = "TGZ,TJZ"
                        },
                        new
                        {
                            Code = new Guid("b9f46974-ef79-4c50-bb68-347e0665b947"),
                            Name = "哈尼族",
                            Sort = 16,
                            Spell = "HNZ"
                        },
                        new
                        {
                            Code = new Guid("2638dd1c-d78d-4eaa-b577-3e89463229fb"),
                            Name = "哈萨克族",
                            Sort = 17,
                            Spell = "HSKZ"
                        },
                        new
                        {
                            Code = new Guid("2052b3c4-99b9-4ba3-b631-c425bfd8056e"),
                            Name = "傣族",
                            Sort = 18,
                            Spell = "DZ"
                        },
                        new
                        {
                            Code = new Guid("bfc768c1-6728-4c81-8033-ea359620e6ad"),
                            Name = "黎族",
                            Sort = 19,
                            Spell = "LZ"
                        },
                        new
                        {
                            Code = new Guid("8dae7979-f7ed-4251-ae1a-2e4e26153651"),
                            Name = "傈僳族",
                            Sort = 20,
                            Spell = "LSZ"
                        },
                        new
                        {
                            Code = new Guid("10645c61-d75d-4370-892c-cb51c3753a22"),
                            Name = "佤族",
                            Sort = 21,
                            Spell = "WZ"
                        },
                        new
                        {
                            Code = new Guid("3a582cd2-b976-4ccf-bd1e-0957080a372b"),
                            Name = "畲族",
                            Sort = 22,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("357748b8-2a3b-41c5-b0c6-38f589a9a021"),
                            Name = "高山族",
                            Sort = 23,
                            Spell = "GSZ"
                        },
                        new
                        {
                            Code = new Guid("6d676c8b-3249-43a0-82df-6cf818089112"),
                            Name = "拉祜族",
                            Sort = 24,
                            Spell = "LHZ"
                        },
                        new
                        {
                            Code = new Guid("ec6688fc-809b-4990-98ec-19be9e08490f"),
                            Name = "水族",
                            Sort = 25,
                            Spell = "SZ"
                        },
                        new
                        {
                            Code = new Guid("81e1f806-f6b6-485a-a7ae-cb4c31f76898"),
                            Name = "东乡族",
                            Sort = 26,
                            Spell = "DXZ"
                        },
                        new
                        {
                            Code = new Guid("e478d2d5-da32-45a6-a56b-e99254688eae"),
                            Name = "纳西族",
                            Sort = 27,
                            Spell = "NXZ"
                        },
                        new
                        {
                            Code = new Guid("efd6bd4f-8eb9-4118-859b-cbb660ca8741"),
                            Name = "景颇族",
                            Sort = 28,
                            Spell = "JPZ"
                        },
                        new
                        {
                            Code = new Guid("d4ba2408-443e-4279-841b-5bf856920e99"),
                            Name = "柯尔克孜族",
                            Sort = 29,
                            Spell = "KEKZZ"
                        },
                        new
                        {
                            Code = new Guid("45a2357e-d525-4583-8788-2b11fa2b932f"),
                            Name = "土族",
                            Sort = 30,
                            Spell = "TZ"
                        },
                        new
                        {
                            Code = new Guid("8eb796ca-7875-4233-bea7-5ec5833b2937"),
                            Name = "达斡尔族",
                            Sort = 31,
                            Spell = "DWEZ"
                        },
                        new
                        {
                            Code = new Guid("152307be-cbdc-4720-bf2d-9664fc7b0904"),
                            Name = "仫佬族",
                            Sort = 32,
                            Spell = "MLZ"
                        },
                        new
                        {
                            Code = new Guid("3ca80594-40d6-486b-be1c-48bbae272080"),
                            Name = "羌族",
                            Sort = 33,
                            Spell = "QZ"
                        },
                        new
                        {
                            Code = new Guid("1209f40f-796b-4d69-b525-ef697931f646"),
                            Name = "布朗族",
                            Sort = 34,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("9abc7544-4ad8-4f5f-a14f-bea6d13a9b33"),
                            Name = "撒拉族",
                            Sort = 35,
                            Spell = "SLZ"
                        },
                        new
                        {
                            Code = new Guid("7f16ddf8-1f31-4ce1-bd9e-176bc1b0dbdb"),
                            Name = "毛难族",
                            Sort = 36,
                            Spell = "MNZ"
                        },
                        new
                        {
                            Code = new Guid("168b895a-b4d5-456e-b37e-1e6bb4f78bab"),
                            Name = "仡佬族",
                            Sort = 37,
                            Spell = "GLZ,YLZ"
                        },
                        new
                        {
                            Code = new Guid("d574499a-6039-4bd3-8da2-5164641fa549"),
                            Name = "锡伯族",
                            Sort = 38,
                            Spell = "XBZ"
                        },
                        new
                        {
                            Code = new Guid("466c23f4-c7e4-440d-804f-ebf1cb76549e"),
                            Name = "阿昌族",
                            Sort = 39,
                            Spell = "ACZ,ECZ"
                        },
                        new
                        {
                            Code = new Guid("2f79f709-f806-4046-bc28-159bca335ca9"),
                            Name = "普米族",
                            Sort = 40,
                            Spell = "PMZ"
                        },
                        new
                        {
                            Code = new Guid("eacd5cca-8c3d-4d4f-b473-0e5aea715955"),
                            Name = "塔吉克族",
                            Sort = 41,
                            Spell = "DJKZ,TJKZ"
                        },
                        new
                        {
                            Code = new Guid("51c37d55-610e-481e-a9d6-5f97d685c09d"),
                            Name = "怒族",
                            Sort = 42,
                            Spell = "NZ"
                        },
                        new
                        {
                            Code = new Guid("0f0a108b-6c5a-4943-ac23-ab53efda7099"),
                            Name = "乌孜别克族",
                            Sort = 43,
                            Spell = "WZBKZ"
                        },
                        new
                        {
                            Code = new Guid("ce579cb3-a590-4696-a77b-51cb8727d9e2"),
                            Name = "俄罗斯族",
                            Sort = 44,
                            Spell = "ELSZ"
                        },
                        new
                        {
                            Code = new Guid("44f23afe-0a55-433d-8e4d-d95ab39e5e73"),
                            Name = "鄂温克族",
                            Sort = 45,
                            Spell = "EWKZ"
                        },
                        new
                        {
                            Code = new Guid("3123a89d-e97b-4491-bc4d-32cd31511694"),
                            Name = "崩龙族",
                            Sort = 46,
                            Spell = "BLZ"
                        },
                        new
                        {
                            Code = new Guid("ec0e8873-2ba6-472b-a943-6ef5c2eb8d59"),
                            Name = "保安族",
                            Sort = 47,
                            Spell = "BAZ"
                        },
                        new
                        {
                            Code = new Guid("14c4aabf-833d-4ce2-ad6b-4c565f6f7e92"),
                            Name = "裕固族",
                            Sort = 48,
                            Spell = "YGZ"
                        },
                        new
                        {
                            Code = new Guid("20dec25c-d768-47c7-ab12-5ec904d6e26b"),
                            Name = "京族",
                            Sort = 49,
                            Spell = "JZ"
                        },
                        new
                        {
                            Code = new Guid("f9cd6996-7b08-4799-832a-683501c5b385"),
                            Name = "塔塔尔族",
                            Sort = 50,
                            Spell = "DDEZ,TDEZ,DTEZ,TTEZ"
                        },
                        new
                        {
                            Code = new Guid("99e41b02-9ec1-4fbb-97e2-f493259a3ad8"),
                            Name = "独龙族",
                            Sort = 51,
                            Spell = "DLZ"
                        },
                        new
                        {
                            Code = new Guid("92c9a26e-67d9-4782-a96c-c0c104aa150d"),
                            Name = "鄂伦春族",
                            Sort = 52,
                            Spell = "ELCZ"
                        },
                        new
                        {
                            Code = new Guid("accf852a-a4e0-4b25-b12e-21e645d785cb"),
                            Name = "赫哲族",
                            Sort = 53,
                            Spell = "HZZ"
                        },
                        new
                        {
                            Code = new Guid("83a97d2d-35fe-4d28-92d2-e50fd499710a"),
                            Name = "门巴族",
                            Sort = 54,
                            Spell = "MBZ"
                        },
                        new
                        {
                            Code = new Guid("d6f7df00-b722-4e70-b4f7-88845fb0e539"),
                            Name = "珞巴族",
                            Sort = 55,
                            Spell = "LBZ"
                        },
                        new
                        {
                            Code = new Guid("c14ef177-26b5-4e27-97e8-db922f11bb46"),
                            Name = "基诺族",
                            Sort = 56,
                            Spell = "JNZ"
                        },
                        new
                        {
                            Code = new Guid("d7d1e688-e40b-48f2-9573-6d152dddcb95"),
                            Name = "其他",
                            Sort = 57,
                            Spell = "JT,QT"
                        },
                        new
                        {
                            Code = new Guid("efc4b81d-d65d-4573-aad5-7a01df71402c"),
                            Name = "外国血统中国人士",
                            Sort = 58,
                            Spell = "WGXTZGRS"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComPolitical", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComPolitical");

                    b.HasData(
                        new
                        {
                            Code = new Guid("0c263995-d371-4895-b95f-4a58850f19c8"),
                            Name = "中共党员",
                            Sort = 1,
                            Spell = "ZGDY"
                        },
                        new
                        {
                            Code = new Guid("14c293bc-1c6e-491b-a0e6-c0cad522794a"),
                            Name = "中共预备党员",
                            Sort = 2,
                            Spell = "ZGYBDY"
                        },
                        new
                        {
                            Code = new Guid("fa1aaf53-c56b-445a-a32f-c48d90892ad2"),
                            Name = "共青团员",
                            Sort = 3,
                            Spell = "GQTY"
                        },
                        new
                        {
                            Code = new Guid("4aba41fb-16be-42f1-bd22-74d6fe891749"),
                            Name = "民革党员",
                            Sort = 4,
                            Spell = "MGDY,MJDY"
                        },
                        new
                        {
                            Code = new Guid("707d385f-04d8-4185-b7d5-b60f603fb6fa"),
                            Name = "民盟盟员",
                            Sort = 5,
                            Spell = "MMMY"
                        },
                        new
                        {
                            Code = new Guid("595aa4b3-c527-47bb-a8cc-22599a409b06"),
                            Name = "民建会员",
                            Sort = 6,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("d6867a95-76dc-42c1-a6ff-c42e521581dd"),
                            Name = "民进会员",
                            Sort = 7,
                            Spell = "MJHY,MJKY"
                        },
                        new
                        {
                            Code = new Guid("f518f303-6559-4475-9950-9e49588e8f2a"),
                            Name = "农工党党员",
                            Sort = 8,
                            Spell = "NGDDY"
                        },
                        new
                        {
                            Code = new Guid("b68b4038-45c6-4aed-aab3-217059eec489"),
                            Name = "致公党党员",
                            Sort = 9,
                            Spell = "ZGDDY"
                        },
                        new
                        {
                            Code = new Guid("e6591dcc-f1ce-47ab-8ee6-e495d7700c58"),
                            Name = "九三学社社员",
                            Sort = 10,
                            Spell = "JSXSSY"
                        },
                        new
                        {
                            Code = new Guid("b068773f-bd95-49e8-8a0b-852f5221e3f5"),
                            Name = "台盟盟员",
                            Sort = 11,
                            Spell = "TMMY"
                        },
                        new
                        {
                            Code = new Guid("98e5c6ba-d933-400c-b6cf-11ad60b7ed7c"),
                            Name = "无党派人士",
                            Sort = 12,
                            Spell = "MDPRS,WDPRS"
                        },
                        new
                        {
                            Code = new Guid("8e871348-b291-44e3-9aff-534cfe8eb4cf"),
                            Name = "群众",
                            Sort = 13,
                            Spell = "QZ"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComPost", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComPost");

                    b.HasData(
                        new
                        {
                            Code = new Guid("62d5a48c-5452-488d-a1ea-6078949db110"),
                            Name = "卫",
                            Sort = 1,
                            Spell = "W"
                        },
                        new
                        {
                            Code = new Guid("009a0766-43e0-4cda-a008-e705d8604dab"),
                            Name = "工",
                            Sort = 2,
                            Spell = "G"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("LevelCode");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("LevelCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("ComProfessionTitle");

                    b.HasData(
                        new
                        {
                            Code = new Guid("3649058d-92cb-4351-be67-134df9c1be8e"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任医师",
                            Sort = 1,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("947ed658-509e-4573-9c41-3399c56f6165"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任药师",
                            Sort = 2,
                            Spell = "ZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("906f1fd7-ef2e-440b-8b52-d97d957db8ef"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任护师",
                            Sort = 3,
                            Spell = "ZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("c3f78bcf-7fa6-4e72-8aa2-1c7ed124d54b"),
                            LevelCode = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "主任技师",
                            Sort = 4,
                            Spell = "ZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("ed5f7df2-d03f-43b7-b895-c153ca680603"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任医师",
                            Sort = 5,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("5d426158-538b-4cdb-aa20-5223fe0b9036"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任药师",
                            Sort = 6,
                            Spell = "FZRYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("c21685da-fa19-47dc-bfa8-e00c1652b772"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任护师",
                            Sort = 7,
                            Spell = "FZRHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("8ff47f93-3e38-49a5-b274-fa36c9f77389"),
                            LevelCode = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副主任技师",
                            Sort = 8,
                            Spell = "FZRJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("bb0c94d0-cb37-4344-9b25-1f661a377277"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主治医师",
                            Sort = 9,
                            Spell = "ZZYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("16271a5b-ba0b-49ff-9563-633adcda5016"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管药师",
                            Sort = 10,
                            Spell = "ZGYS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("d5595f16-7642-4815-8131-1b6d705068e3"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管护师",
                            Sort = 11,
                            Spell = "ZGHS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("5dea5587-8714-4a02-a6e9-62f77929eb13"),
                            LevelCode = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "主管技师",
                            Sort = 12,
                            Spell = "ZGJS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("98f932ad-ce19-4389-a0f3-ebb096a55f46"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医师",
                            Sort = 13,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("a34f639b-4559-40f0-87b9-1e71f2b3e288"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "医士",
                            Sort = 14,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("da7ed7e3-a260-45d7-b4ac-9bc588578ad0"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药师",
                            Sort = 15,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("7252961d-20cf-4e8f-bd17-ade5c64fe857"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "药士",
                            Sort = 16,
                            Spell = "YS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("6b7d5e1a-5c5d-4f90-b829-276d8f217ef2"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护师",
                            Sort = 17,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("7ec6cc3a-7efe-44e4-a76a-3142fcd47513"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "护士",
                            Sort = 18,
                            Spell = "HS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("ea08db48-01f2-4ead-9a07-c303d3762706"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技师",
                            Sort = 19,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("01210774-9c9f-48f3-b750-dfb1ea5f4d97"),
                            LevelCode = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "技士",
                            Sort = 20,
                            Spell = "JS",
                            TypeCode = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768")
                        },
                        new
                        {
                            Code = new Guid("ee287ca4-f361-4ee5-82d0-764ed3a164fc"),
                            LevelCode = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无职称",
                            Sort = 21,
                            Spell = "MZC,WZC",
                            TypeCode = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleLevel");

                    b.HasData(
                        new
                        {
                            Code = new Guid("9ee36b90-1e89-4591-b849-9d79badce3a8"),
                            Name = "正高级",
                            Sort = 1,
                            Spell = "ZGJ"
                        },
                        new
                        {
                            Code = new Guid("4ef010d0-5c7e-4e38-bcff-fffcd69627cf"),
                            Name = "副高级",
                            Sort = 2,
                            Spell = "FGJ"
                        },
                        new
                        {
                            Code = new Guid("f469629a-4d6d-4640-804b-f2e5c44f5ca4"),
                            Name = "中级",
                            Sort = 3,
                            Spell = "ZJ"
                        },
                        new
                        {
                            Code = new Guid("4e8d76cd-5bc0-4281-8e68-446a8b649b82"),
                            Name = "初级",
                            Sort = 4,
                            Spell = "CJ"
                        },
                        new
                        {
                            Code = new Guid("2d9f5ae2-a9b1-497f-97f4-e31cfe6f0ba0"),
                            Name = "无",
                            Sort = 5,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitleType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("ComProfessionTitleType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("b9bbcf12-f2c7-48e1-9ece-12068ac58768"),
                            Name = "卫生技术人员",
                            Sort = 1,
                            Spell = "WSJSRY,WSJZRY"
                        },
                        new
                        {
                            Code = new Guid("8eed4cff-7f80-4ecf-990a-c6888be90933"),
                            Name = "高等学校教师",
                            Sort = 2,
                            Spell = "GDXJJS,GDXXJS"
                        },
                        new
                        {
                            Code = new Guid("aa47aa17-feb8-4988-850d-ac152aab6a42"),
                            Name = "中等专业学校教师",
                            Sort = 3,
                            Spell = "ZDZYXJJS,ZDZYXXJS"
                        },
                        new
                        {
                            Code = new Guid("55911415-fae3-489d-aaad-d62909abc425"),
                            Name = "技工学校教师",
                            Sort = 4,
                            Spell = "JGXJJS,JGXXJS"
                        },
                        new
                        {
                            Code = new Guid("e3540f40-d87a-4237-ad66-6361a8544e06"),
                            Name = "中学教师",
                            Sort = 5,
                            Spell = "ZXJS"
                        },
                        new
                        {
                            Code = new Guid("5b93f809-8fc1-4536-8303-de486848429d"),
                            Name = "小学（幼儿园）教师",
                            Sort = 6,
                            Spell = "XX（YEY）JS"
                        },
                        new
                        {
                            Code = new Guid("fe6ed81e-c725-4229-9c20-a412502d07ce"),
                            Name = "自然科学研究人员",
                            Sort = 7,
                            Spell = "ZRKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("23fd2ad4-a4f8-421e-8e40-4bcfa7c0b235"),
                            Name = "社会科学研究人员",
                            Sort = 8,
                            Spell = "SHKXYJRY,SKKXYJRY"
                        },
                        new
                        {
                            Code = new Guid("1c99a8f6-95eb-4509-a324-88062cb347db"),
                            Name = "工程技术人员",
                            Sort = 9,
                            Spell = "GCJSRY,GCJZRY"
                        },
                        new
                        {
                            Code = new Guid("38dc4446-2fa4-4cf6-95a5-4e1fdb80ec3e"),
                            Name = "实验技术人员",
                            Sort = 10,
                            Spell = "SYJSRY,SYJZRY"
                        },
                        new
                        {
                            Code = new Guid("0f456314-ca2b-4348-a9ba-8006f2ff0d3f"),
                            Name = "农业技术人员",
                            Sort = 11,
                            Spell = "NYJSRY,NYJZRY"
                        },
                        new
                        {
                            Code = new Guid("1abc51e0-7961-4191-85be-c0d6f326ade8"),
                            Name = "经济专业人员",
                            Sort = 12,
                            Spell = "JJZYRY"
                        },
                        new
                        {
                            Code = new Guid("69eb6a4c-e0c3-488a-8c3a-2df5e48ce834"),
                            Name = "会计专业人员",
                            Sort = 13,
                            Spell = "HJZYRY,KJZYRY"
                        },
                        new
                        {
                            Code = new Guid("b192f724-a637-4e58-ac67-c3365800c79f"),
                            Name = "审计专业人员",
                            Sort = 14,
                            Spell = "SJZYRY"
                        },
                        new
                        {
                            Code = new Guid("433234ac-9c1a-41be-af32-b3c59c325e34"),
                            Name = "统计专业人员",
                            Sort = 15,
                            Spell = "TJZYRY"
                        },
                        new
                        {
                            Code = new Guid("1fbf0519-36d5-4c20-b275-d108ec299ac3"),
                            Name = "新闻专业人员",
                            Sort = 16,
                            Spell = "XWZYRY"
                        },
                        new
                        {
                            Code = new Guid("5cce4e5d-c263-44b3-aa02-61404082f39e"),
                            Name = "出版专业人员",
                            Sort = 17,
                            Spell = "CBZYRY"
                        },
                        new
                        {
                            Code = new Guid("6e3ee3de-2b73-4858-865b-7476124b4f81"),
                            Name = "图书资料专业人员",
                            Sort = 18,
                            Spell = "TSZLZYRY"
                        },
                        new
                        {
                            Code = new Guid("62ebd591-0c68-4e6e-9bc0-24ed9e64611e"),
                            Name = "文物博物专业人员",
                            Sort = 19,
                            Spell = "WWBWZYRY"
                        },
                        new
                        {
                            Code = new Guid("84827a85-670c-4d28-ab54-11efcf04f353"),
                            Name = "档案专业人员",
                            Sort = 20,
                            Spell = "DAZYRY"
                        },
                        new
                        {
                            Code = new Guid("52a6e3f0-df88-4354-bee4-2deac97bfb25"),
                            Name = "广播电视播音人员",
                            Sort = 21,
                            Spell = "ABDSBYRY,GBDSBYRY"
                        },
                        new
                        {
                            Code = new Guid("ab8e374f-da79-4be5-a46c-4de747c78812"),
                            Name = "翻译人员",
                            Sort = 22,
                            Spell = "FYRY"
                        },
                        new
                        {
                            Code = new Guid("ee15a20a-be29-4d7e-a95c-51e51ef398c8"),
                            Name = "律师",
                            Sort = 23,
                            Spell = "LS"
                        },
                        new
                        {
                            Code = new Guid("8ea26d25-52bc-444a-9c12-f84518078fae"),
                            Name = "公证员",
                            Sort = 24,
                            Spell = "GZY"
                        },
                        new
                        {
                            Code = new Guid("aa276c49-bdd3-4f16-bd51-0d5317881d64"),
                            Name = "海关人员",
                            Sort = 25,
                            Spell = "HGRY"
                        },
                        new
                        {
                            Code = new Guid("4ea883d8-cf16-4a6e-8a5a-9b0b3f036708"),
                            Name = "船舶技术人员",
                            Sort = 26,
                            Spell = "CBJSRY,CBJZRY"
                        },
                        new
                        {
                            Code = new Guid("f632075f-081a-416c-a69b-2f71a36e1de6"),
                            Name = "民用航空飞行技术人员",
                            Sort = 27,
                            Spell = "MYHKFHJSRY,MYHKFXJSRY,MYHKFHJZRY,MYHKFXJZRY"
                        },
                        new
                        {
                            Code = new Guid("828b4c4d-a1a6-488d-9a1e-e23ff1c070e0"),
                            Name = "艺术专业人员",
                            Sort = 28,
                            Spell = "YSZYRY,YZZYRY"
                        },
                        new
                        {
                            Code = new Guid("fbb926df-0ce9-4b84-94a5-b39176c6a88e"),
                            Name = "工艺美术专业人员",
                            Sort = 29,
                            Spell = "GYMSZYRY,GYMZZYRY"
                        },
                        new
                        {
                            Code = new Guid("e7037510-b73b-4f75-8cc2-46aa85b9d1a3"),
                            Name = "体育教练员",
                            Sort = 30,
                            Spell = "TYJLY"
                        },
                        new
                        {
                            Code = new Guid("d662f8f0-d434-467b-81fc-1e1abaa831b0"),
                            Name = "思想政治工作人员",
                            Sort = 31,
                            Spell = "SXZZGZRY"
                        },
                        new
                        {
                            Code = new Guid("f20164e3-99ce-42ba-ac19-f6bd740ed46c"),
                            Name = "无",
                            Sort = 32,
                            Spell = "M,W"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysDept", b =>
                {
                    b.Property<string>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("DeptName")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("DeptCode");

                    b.ToTable("SysDept");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.Property<string>("EmpCode")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AdminDutyCode");

                    b.Property<int>("Age");

                    b.Property<string>("ArchivesNo");

                    b.Property<string>("BankCard");

                    b.Property<DateTime>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid?>("ComPostCode");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateEmp");

                    b.Property<Guid?>("DegreeCode");

                    b.Property<string>("DeptCode")
                        .IsRequired();

                    b.Property<Guid?>("EducationCode");

                    b.Property<DateTime?>("EducationDate");

                    b.Property<string>("EmpName")
                        .IsRequired();

                    b.Property<Guid>("GenderCode");

                    b.Property<DateTime?>("GraduationDate");

                    b.Property<string>("HomeAdd");

                    b.Property<int>("HospitalAge");

                    b.Property<DateTime>("HospitalDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("IdentityAdd");

                    b.Property<string>("IdentityCard")
                        .IsRequired();

                    b.Property<bool>("IsPost")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStop")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("MarriageCode");

                    b.Property<Guid>("NationCode");

                    b.Property<string>("NativePlace");

                    b.Property<string>("OldName");

                    b.Property<string>("OpenBank");

                    b.Property<string>("Photo");

                    b.Property<Guid>("PoliticalCode");

                    b.Property<DateTime?>("PoliticalDate");

                    b.Property<Guid>("PostCode");

                    b.Property<string>("Practice");

                    b.Property<DateTime?>("PracticeDate");

                    b.Property<Guid?>("ProfessionTitleCode");

                    b.Property<Guid?>("ProfessionTitleLevelCode");

                    b.Property<Guid?>("ProfessionTitleTypeCode");

                    b.Property<string>("PublicMoneyNo");

                    b.Property<string>("Remark");

                    b.Property<string>("School");

                    b.Property<string>("SchoolMajor");

                    b.Property<string>("SocialInsuranceNo");

                    b.Property<string>("Spell");

                    b.Property<string>("Telephone");

                    b.Property<Guid>("TypeCode");

                    b.Property<int>("WorkAge");

                    b.Property<DateTime?>("WorkDate");

                    b.HasKey("EmpCode");

                    b.HasIndex("AdminDutyCode");

                    b.HasIndex("ComPostCode");

                    b.HasIndex("DegreeCode");

                    b.HasIndex("DeptCode");

                    b.HasIndex("EducationCode");

                    b.HasIndex("GenderCode");

                    b.HasIndex("MarriageCode");

                    b.HasIndex("NationCode");

                    b.HasIndex("PoliticalCode");

                    b.HasIndex("ProfessionTitleCode");

                    b.HasIndex("ProfessionTitleLevelCode");

                    b.HasIndex("ProfessionTitleTypeCode");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysEmp");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmpType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysEmpType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("90b1984b-3a7b-4925-bb7a-98d97b612362"),
                            Name = "在编人员",
                            Sort = 1,
                            Spell = "ZBRY"
                        },
                        new
                        {
                            Code = new Guid("7141605b-d1eb-410e-b966-eafde0b823c9"),
                            Name = "人事代理",
                            Sort = 2,
                            Spell = "RSDL"
                        },
                        new
                        {
                            Code = new Guid("b1684ad9-ab97-416e-a9e9-0c442f02a2d8"),
                            Name = "临时人员",
                            Sort = 3,
                            Spell = "LSRY"
                        },
                        new
                        {
                            Code = new Guid("456c2106-89f9-4e92-9008-b281b7cb85cc"),
                            Name = "离退人员",
                            Sort = 4,
                            Spell = "LTRY"
                        },
                        new
                        {
                            Code = new Guid("ecbaadc8-5eea-436f-85d4-4a47482760e6"),
                            Name = "辞职人员",
                            Sort = 5,
                            Spell = "CZRY"
                        },
                        new
                        {
                            Code = new Guid("9b1848f4-8315-4cb8-9f5e-8a54f0804d92"),
                            Name = "返聘人员",
                            Sort = 6,
                            Spell = "FPRY"
                        },
                        new
                        {
                            Code = new Guid("1721f7e4-e431-4173-9145-91018cd27518"),
                            Name = "调出人员",
                            Sort = 7,
                            Spell = "DCRY,TCRY"
                        },
                        new
                        {
                            Code = new Guid("adea9395-64c6-46be-9f82-8e720f3078f1"),
                            Name = "除名人员",
                            Sort = 8,
                            Spell = "CMRY"
                        },
                        new
                        {
                            Code = new Guid("13633d73-053c-4000-b2d5-90a04273df5c"),
                            Name = "实习进修",
                            Sort = 9,
                            Spell = "SXJX"
                        },
                        new
                        {
                            Code = new Guid("83825404-512a-4400-bb34-9de9a2dd6ff1"),
                            Name = "借出人员",
                            Sort = 10,
                            Spell = "JCRY"
                        },
                        new
                        {
                            Code = new Guid("0fd30ada-d031-46df-ace5-2f0a9c95ffd9"),
                            Name = "长期出国人员",
                            Sort = 11,
                            Spell = "CJCGRY,ZJCGRY,CQCGRY,ZQCGRY"
                        },
                        new
                        {
                            Code = new Guid("82133b64-c8de-491a-afa8-d52954c3fe7f"),
                            Name = "自动离职人员",
                            Sort = 12,
                            Spell = "ZDLZRY"
                        },
                        new
                        {
                            Code = new Guid("c008e596-f50d-478b-87a0-039f9b32fe8e"),
                            Name = "停薪留职人员",
                            Sort = 13,
                            Spell = "TXLZRY"
                        },
                        new
                        {
                            Code = new Guid("92fd27bc-4d2c-4f98-b8e6-512d7f26b270"),
                            Name = "编外离岗人员",
                            Sort = 14,
                            Spell = "BWLGRY"
                        },
                        new
                        {
                            Code = new Guid("4913df20-319c-4019-b89a-8cc89b015623"),
                            Name = "内部退养",
                            Sort = 15,
                            Spell = "NBTY"
                        },
                        new
                        {
                            Code = new Guid("440ad1b9-4aa1-4c4f-a42b-00fd4b072323"),
                            Name = "试用人员",
                            Sort = 16,
                            Spell = "SYRY"
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Action");

                    b.Property<string>("Controller");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.Property<Guid>("TypeCode");

                    b.HasKey("Code");

                    b.HasIndex("TypeCode");

                    b.ToTable("SysNavbar");

                    b.HasData(
                        new
                        {
                            Code = new Guid("94183da2-9554-4767-bc57-fe32a2fa536a"),
                            Action = "Index",
                            Controller = "SysNavbarType",
                            Name = "菜单类别",
                            Sort = 1,
                            Spell = "CCLB,CDLB,CSLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("5be1e55c-b6d7-48a0-b4a1-5118d975a785"),
                            Action = "Index",
                            Controller = "SysNavbar",
                            Name = "菜单",
                            Sort = 2,
                            Spell = "CC,CD,CS",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("c3408793-ee8c-41f3-b8f8-6f24cb5d3d67"),
                            Action = "Index",
                            Controller = "ComGender",
                            Name = "性别",
                            Sort = 3,
                            Spell = "XB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("837e43c7-993f-4813-bf41-c53e7ae7881b"),
                            Action = "Index",
                            Controller = "ComNation",
                            Name = "民族",
                            Sort = 4,
                            Spell = "MZ",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("880c9ae9-7d0e-4ceb-a1ce-a9f14b09323a"),
                            Action = "Index",
                            Controller = "ComPolitical",
                            Name = "政治面貌",
                            Sort = 5,
                            Spell = "ZZMM",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("ab72c428-66ee-4f4f-b737-24f49011360a"),
                            Action = "Index",
                            Controller = "ComProfessionTitleType",
                            Name = "职称系列",
                            Sort = 6,
                            Spell = "ZCJL,ZCXL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("ffa2aab6-a2f7-4f84-96e9-e5e693cfe295"),
                            Action = "Index",
                            Controller = "ComProfessionTitleLevel",
                            Name = "职称级别",
                            Sort = 7,
                            Spell = "ZCJB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("8a76b950-f16f-475d-bb8a-dcc0269aad4a"),
                            Action = "Index",
                            Controller = "ComProfessionTitle",
                            Name = "职称",
                            Sort = 8,
                            Spell = "ZC",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("8bea0ab3-f76a-47f7-b886-c65081ac7dc2"),
                            Action = "Index",
                            Controller = "ComAdminDuty",
                            Name = "行政职务",
                            Sort = 9,
                            Spell = "HZZW,XZZW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("440aa228-85ef-41e1-9a7e-1a0f2e08cfa5"),
                            Action = "Index",
                            Controller = "SysEmpType",
                            Name = "人员类别",
                            Sort = 10,
                            Spell = "RYLB",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("7da9fda9-f37d-4d93-bf78-ccced1ed7728"),
                            Action = "Index",
                            Controller = "ComEducation",
                            Name = "学历",
                            Sort = 11,
                            Spell = "XL",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("008fb261-dca0-4c5b-8859-b4fcbd0dcbb5"),
                            Action = "Index",
                            Controller = "ComDegree",
                            Name = "学位",
                            Sort = 12,
                            Spell = "XW",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("f00e8e02-05a5-473b-adc5-fae9a550e78d"),
                            Action = "Index",
                            Controller = "ComMarriage",
                            Name = "婚姻状况",
                            Sort = 13,
                            Spell = "HYZK",
                            TypeCode = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc")
                        },
                        new
                        {
                            Code = new Guid("62848550-deca-405a-a287-fcd8f7d9ace9"),
                            Action = "Index",
                            Controller = "SysDept",
                            Name = "科室信息",
                            Sort = 14,
                            Spell = "KSXX",
                            TypeCode = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e")
                        },
                        new
                        {
                            Code = new Guid("6b685328-3999-4c34-b16f-b1200916a448"),
                            Action = "Index",
                            Controller = "SysEmp",
                            Name = "人员管理",
                            Sort = 15,
                            Spell = "RYGL",
                            TypeCode = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993")
                        });
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbarType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Spell");

                    b.HasKey("Code");

                    b.ToTable("SysNavbarType");

                    b.HasData(
                        new
                        {
                            Code = new Guid("4d3c3953-fd9e-4df1-aa18-3285e020d4bc"),
                            Name = "基础数据维护",
                            Sort = 1,
                            Spell = "JCSJWH"
                        },
                        new
                        {
                            Code = new Guid("c4aa85c9-bd15-47e7-bc1f-b7fd24c7a52e"),
                            Name = "机构管理",
                            Sort = 2,
                            Spell = "JGGL"
                        },
                        new
                        {
                            Code = new Guid("f356c105-78d1-4d16-bb8d-a48fc1072993"),
                            Name = "人事档案",
                            Sort = 3,
                            Spell = "RSDA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.ComProfessionTitle", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("LevelCode")
                        .HasConstraintName("FK_LevelCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("ComProfessionTitles")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_ComProfessionTitle")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysEmp", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.ComAdminDuty", "ComAdminDuty")
                        .WithMany("SysEmps")
                        .HasForeignKey("AdminDutyCode")
                        .HasConstraintName("FK_AdminDutyCode_ComAdminDuty_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComPost", "ComPost")
                        .WithMany("SysEmps")
                        .HasForeignKey("ComPostCode");

                    b.HasOne("HospitalPersonnelSystem.Models.ComDegree", "ComDegree")
                        .WithMany("SysEmps")
                        .HasForeignKey("DegreeCode")
                        .HasConstraintName("FK_DegreeCode_ComDegree_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysDept", "SysDept")
                        .WithMany("SysEmps")
                        .HasForeignKey("DeptCode")
                        .HasConstraintName("FK_DeptCode_SysDept_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComEducation", "ComEducation")
                        .WithMany("SysEmps")
                        .HasForeignKey("EducationCode")
                        .HasConstraintName("FK_EducationCode_ComEducation_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComGender", "ComGender")
                        .WithMany("SysEmps")
                        .HasForeignKey("GenderCode")
                        .HasConstraintName("FK_GenderCode_ComGender_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComMarriage", "ComMarriage")
                        .WithMany("SysEmps")
                        .HasForeignKey("MarriageCode")
                        .HasConstraintName("FK_MarriageCode_ComMarriage_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComNation", "ComNation")
                        .WithMany("SysEmps")
                        .HasForeignKey("NationCode")
                        .HasConstraintName("FK_NationCode_ComNation_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComPolitical", "ComPolitical")
                        .WithMany("SysEmps")
                        .HasForeignKey("PoliticalCode")
                        .HasConstraintName("FK_PoliticalCode_ComPolitical_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitle", "ComProfessionTitle")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleCode")
                        .HasConstraintName("FK_PTCode_ComProfessionTitle_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleLevel", "ComProfessionTitleLevel")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleLevelCode")
                        .HasConstraintName("FK_PTLCode_ComProfessionTitleLevel_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.ComProfessionTitleType", "ComProfessionTitleType")
                        .WithMany("SysEmps")
                        .HasForeignKey("ProfessionTitleTypeCode")
                        .HasConstraintName("FK_PTTCode_ComProfessionTitleType_SysEmp");

                    b.HasOne("HospitalPersonnelSystem.Models.SysEmpType", "SysEmpType")
                        .WithMany("SysEmps")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysEmpType_SysEmp")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalPersonnelSystem.Models.SysNavbar", b =>
                {
                    b.HasOne("HospitalPersonnelSystem.Models.SysNavbarType", "SysNavbarType")
                        .WithMany("SysNavbars")
                        .HasForeignKey("TypeCode")
                        .HasConstraintName("FK_TypeCode_SysNavbarType_SysNavbar")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
